---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, service connectors, what are connectors, what is a connector, what"s a connector, days, 14 days' 
summary: 在大多數情況下、您需要在雲端或內部部署網路中部署 Connector 。Connector 可讓 Cloud Manager 管理公有雲環境中的資源與程序。 
---
= 深入瞭解連接器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在大多數情況下、Cloud Manager帳戶管理員需要在雲端或內部部署網路中部署_Connector_。Connector是Cloud Manager日常使用的重要元件。Connector可讓Cloud Manager管理公有雲環境中的資源與程序。



== 需要連接器時

需要連接器才能使用Cloud Manager中的許多功能和服務。



=== 服務

* Amazon FSX提供ONTAP 功能完善的管理功能
* Amazon S3探索
* Azure Blob探索
* 雲端備份
* 雲端資料感測
* 雲端分層
* Cloud Volumes ONTAP
* E系列系統
* 全域檔案快取
* Google Cloud Storage探索
* Kubernetes叢集
* 監控
* 內部部署 ONTAP 的叢集
* StorageGRID


下列服務需要*非_*連接器：

* 《數位顧問》 Active IQ
* Amazon FSX- ONTAP 用於建立工作環境、而Connector不需要建立工作環境、則需要建立及管理磁碟區、複寫資料、並將FSX與ONTAP NetApp雲端服務整合、例如Data Sense和Cloud Sync Sfor。
* Azure NetApp Files
+
雖然不需要連接器來設定和管理Azure NetApp Files 功能、但如果您想要使用Cloud Data Sense來掃描Azure NetApp Files 支援資料、則需要連接器。

* 適用於 Google Cloud Cloud Volumes Service
* Cloud Sync




=== 數位錢包

在幾乎所有情況下、您都可以在沒有連接器的情況下、將授權新增至Digital Wallet。

連接器新增授權至Digital Wallet所需的唯一時間、是Cloud Volumes ONTAP 針對以節點為基礎的_授權。在這種情況下需要連接器、因為資料是取自Cloud Volumes ONTAP 安裝在效益分析系統上的授權。



== 支援的位置

下列位置支援連接器：

* Amazon Web Services
* Microsoft Azure
* Google Cloud
* 在您的內部環境中
* 不需存取網際網路、就能在內部部署




=== Azure部署注意事項

如果您在Azure中部署Connector、則該連接器應部署在Cloud Volumes ONTAP 其所管理的、或是所管理的各個系統所在的Azure區域 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure區域配對"^] 適用於整個系統。Cloud Volumes ONTAP這項需求可確保Cloud Volumes ONTAP Azure Private Link連線可用於連接至相關的儲存帳戶。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html["瞭Cloud Volumes ONTAP 解如何使用Azure Private Link"^]。



=== Google Cloud部署注意事項

如果您想要在Cloud Volumes ONTAP Google Cloud中建立一個不完整的系統、那麼您也必須在Google Cloud上執行一個Connector。您無法使用在AWS、Azure或內部執行的Connector。



== 連接器應保持運作

連接器應隨時保持執行狀態。這對於您持續啟用的服務健全狀況和營運而言十分重要。

例如、連接器是Cloud Volumes ONTAP 運作過程中的關鍵要素。如果連接器電源關閉、 Cloud Volumes ONTAP 則在與連接器失去通訊超過 14 天之後、將會關閉此功能。



== 如何建立連接器

Cloud Manager帳戶管理員可透過多種方式建立Connector：

* 直接從 Cloud Manager （建議）
+
** link:task-creating-connectors-aws.html["在 AWS 中建立"]
** link:task-creating-connectors-azure.html["在 Azure 中建立"]
** link:task-creating-connectors-gcp.html["在 GCP 中建立"]


* 在您自己的Linux主機上手動安裝軟體
+
** link:task-installing-linux.html["在可存取網際網路的主機上"]
** link:task-install-connector-onprem-no-internet.html["在內部主機上、但無法存取網際網路"]


* 從雲端供應商的市場
+
** link:task-launching-aws-mktp.html["AWS Marketplace"]
** link:task-launching-azure-mktp.html["Azure Marketplace"]




如果您是在政府區域營運、則必須從雲端供應商的市場部署Connector、或在現有的Linux主機上手動安裝Connector軟體。您無法從Cloud Manager的SaaS網站將Connector部署到政府區域。



== 權限

建立 Connector 需要特定權限、而且 Connector 執行個體本身需要另一組權限。



=== 建立 Connector 的權限

從 Cloud Manager 建立 Connector 的使用者需要特定權限、才能在您選擇的雲端供應商中部署執行個體。Cloud Manager 會在您建立 Connector 時提醒您權限要求。

* link:task-creating-connectors-aws.html["檢視所需的AWS權限"]
* link:task-creating-connectors-azure.html["檢視必要的Azure權限"]
* link:task-creating-connectors-gcp.html["檢視必要的Google Cloud權限"]




=== Connector 執行個體的權限

Connector 需要特定的雲端供應商權限、才能代表您執行作業。例如、部署及管理 Cloud Volumes ONTAP 功能。

當您直接從 Cloud Manager 建立 Connector 時、 Cloud Manager 會以所需的權限來建立 Connector 。您無需做任何事。

如果您是從 AWS Marketplace 、 Azure Marketplace 或手動安裝軟體來建立 Connector 、則必須確保擁有適當的權限。

* link:reference-permissions-aws.html["瞭解Connector如何使用AWS權限"]
* link:reference-permissions-azure.html["瞭解Connector如何使用Azure權限"]
* link:reference-permissions-gcp.html["瞭解Connector如何使用Google Cloud權限"]




== 連接器升級

我們通常每個月更新Connector軟體、以引進新功能並改善穩定性。雖然Cloud Manager平台的大部分服務與功能都是透過SaaS型軟體提供、但其中幾項功能和功能則取決於Connector的版本。其中包括Cloud Volumes ONTAP 支援內部的支援、ONTAP 內部的支援、叢集管理、設定及說明。

只要連接器能夠存取傳出的網際網路來取得軟體更新、連接器就會自動將軟體更新至最新版本。



== 每個連接器的工作環境數量

Connector可在Cloud Manager中管理多個工作環境。單一Connector應管理的工作環境數量上限各不相同。這取決於工作環境的類型、磁碟區數量、所管理的容量、以及使用者數量。

如果您有大規模部署、請與NetApp代表合作調整環境規模。如果您在過程中遇到任何問題、請使用產品內對談與我們聯絡。



== 何時使用多個連接器

在某些情況下、您可能只需要一個連接器、但可能需要兩個以上的連接器。

以下是幾個範例：

* 您使用的是多雲端環境（ AWS 和 Azure ）、因此 AWS 中有一個連接器、 Azure 中有另一個連接器。每個系統都能管理 Cloud Volumes ONTAP 在這些環境中執行的不實系統。
* 服務供應商可能會使用一個NetApp帳戶來為客戶提供服務、而使用另一個帳戶來為其中一個業務單位提供災難恢復。每個帳戶都會有個別的 Connectors 。




== 使用具有相同工作環境的多個連接器

您可以同時使用多個連接器來管理工作環境、以便進行災難恢復。如果一個連接器故障、您可以切換至另一個連接器、立即管理工作環境。

若要設定此組態：

. link:task-managing-connectors.html["切換至另一個連接器"]
. 探索現有的工作環境。
+
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-adding-systems.html["將現有Cloud Volumes ONTAP 的不適用系統新增至Cloud Manager"^]
** https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["探索 ONTAP 叢集"^]


. 設定 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage-management.html["容量管理模式"^]
+
只有主連接器應設定為*自動模式*。如果您切換至另一個連接器以進行DR、則可視需要變更容量管理模式。





== 何時在連接器之間切換

當您建立第一個 Connector 時、 Cloud Manager 會針對您所建立的每個額外工作環境、自動使用該 Connector 。建立額外的 Connector 之後、您必須在兩者之間切換、以查看每個 Connector 專屬的工作環境。

link:task-managing-connectors.html["瞭解如何在連接器之間切換"]。



== 本機使用者介面

而您應該從執行幾乎所有的工作 https://cloudmanager.netapp.com["SaaS 使用者介面"^]、連接器上仍有本機使用者介面可供使用。如果您在無法存取網際網路的環境（例如政府區域）中安裝Connector、以及需要從Connector本身執行的幾項工作（而非SaaS介面）、則需要使用此介面：

* link:task-configuring-proxy.html["設定 Proxy 伺服器"]
* 安裝修補程式（您通常會與 NetApp 人員一起安裝修補程式）
* 下載 AutoSupport 資訊（如有問題、通常由 NetApp 人員引導）


link:task-managing-connectors.html#access-the-local-ui["瞭解如何存取本機 UI"]。
