---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agent' 
summary: Connector 是指在雲端網路或內部部署網路中執行的 NetApp 軟體。它會執行 BlueXP 管理資料基礎架構所需執行的動作。Connector 會持續輪詢 BlueXP SaaS 層、以找出需要採取的任何行動。您不需要 Connector 即可開始使用 BlueXP 、但您需要建立 Connector 才能解除鎖定所有 BlueXP 功能和服務。 
---
= 深入瞭解連接器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connector 是您安裝的 NetApp 軟體，可執行 BlueXP  管理儲存基礎架構所需執行的動作。您不需要連接器即可存取 BlueXP  的許多功能，但如果您不需要，則無法使用某些功能。

如果您以標準模式執行 BlueXP  ，就不需要安裝 Connector 來執行 BlueXP  的一些服務，例如軟體更新和數位錢包。不過， BlueXP  的部分優質服務（例如勒索軟體保護或災難恢復）需要您安裝 Connector 。如果您在受限或私人模式下使用 BlueXP  ，則需要安裝 Connector 。



== 在標準模式中，若沒有 Connector ，您可以執行的動作

如果您是以標準模式執行，則可以開始使用 BlueXP  集中管理儲存資源，而無需安裝 Connector 。

您可以在沒有 Connector 的情況下使用下列 BlueXP 功能和服務：

* Amazon FSX for NetApp ONTAP 產品
+
某些動作需要連接器或 BlueXP  工作負載原廠連結。 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["瞭解哪些動作需要連接器或連結"^]

* 自動化目錄
* Azure NetApp Files
+
雖然不需要連接器來設定和管理 Azure NetApp Files 、但如果您想使用 BlueXP 分類來掃描 Azure NetApp Files 資料、則需要連接器。

* 適用於 Google Cloud Cloud Volumes Service
* 複製與同步
* 數位顧問
* 數位錢包（僅限授權，訂閱監控需要 Connector ）
+
在幾乎所有情況下、您都可以在沒有 Connector 的情況下、將授權新增至數位錢包。

+
只有在 Connector 需要將授權新增至數位錢包時、才需要使用 Cloud Volumes ONTAP 節點型授權。需要連接器，因為 BlueXP  需要取得安裝在 Cloud Volumes ONTAP 系統上的授權資料。

* 直接探索內部部署ONTAP 的叢集
+
雖然不需要連接器即可直接探索內部部署ONTAP 的叢集、但如果您想要使用更多的BlueXP功能、則需要連接器。

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["深入瞭解內部ONTAP 部署的叢集探索與管理選項"^]

* 軟體更新
* 永續性
* 工作負載工廠




== 需要連接器時

在標準模式下使用 BlueXP  時，您需要安裝一或多個 Connectors ，才能在 BlueXP  中啟用下列功能和服務：

* 警示
* Amazon FSX提供ONTAP 功能完善的管理功能
* Amazon S3儲存設備
* Azure Blob 儲存設備
* 備份與還原
* 分類
* Cloud Volumes ONTAP
* 災難恢復
* E系列系統
* 經濟效益（僅限檢視）
* Google Cloud Storage 貯體
* 內部部署ONTAP 的不支援叢集整合至BlueXP資料服務
* 營運恢復能力（僅限檢視）
* 勒索軟體保護
* 系統StorageGRID
* 分層
* Volume 快取




== 連接器必須隨時正常運作

由於 Connectors 是 BlueXP  服務架構的基本部分，因此您必須確保相關的 Connectors 隨時正常運作且可存取。雖然這項服務的設計是為了克服連接器可用度的短暫中斷、但您必須在必要時立即採取行動、以補救基礎架構故障。

本文件受EULA規範。如果產品未依照文件操作、則產品的功能與操作、以及您在EULA下的權利、可能會受到不利影響。



=== 對 Cloud Volumes ONTAP 的影響

連接器是Cloud Volumes ONTAP 健全狀況和運作過程中的關鍵要素。如果連接器電源關閉、Cloud Volumes ONTAP 則在與連接器失去通訊超過14天之後、將停止使用以容量為基礎的BYOL系統。這是因為Connector每天都會在系統上重新整理授權。

如果Cloud Volumes ONTAP 您的系統擁有節點型BYOL授權、系統會在14天後繼續執行、因為授權已安裝在Cloud Volumes ONTAP 該系統上。



== 支援的位置

您可以在支援的超大規模環境或內部環境中安裝 Connectors ，視您的需求而定。

* Amazon Web Services
* Microsoft Azure
+
將您的 Connector 部署在與其管理的 Cloud Volumes ONTAP 系統相同的 Azure 區域，或部署在 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure區域配對"^] Cloud Volumes ONTAP 系統的。如此可確保 Cloud Volumes ONTAP 與其相關儲存帳戶之間使用 Azure 私有連結連線。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["瞭Cloud Volumes ONTAP 解如何使用Azure Private Link"^]

* Google Cloud
+
如果您想要搭配 Google Cloud 使用 BlueXP 服務、則必須使用在 Google Cloud 中執行的 Connector 。

* 在您的內部環境中




== 與雲端供應商通訊

Connector 使用 TLS 1.2 與 AWS 、 Azure 和 Google Cloud 進行所有通訊。



== 受限模式和私有模式

若要在受限模式或私有模式下使用 BlueXP 、請先安裝 Connector 、然後存取在 Connector 本機上執行的使用者介面、以開始使用 BlueXP 。

link:concept-modes.html["瞭解 BlueXP 部署模式"]。



== 如何建立連接器

您可以直接從 BlueXP  、雲端供應商的市場、或手動在自己的 Linux 主機上安裝軟體、來建立 Connector 。開始使用的方式取決於您是在標準模式、受限模式或私人模式下使用 BlueXP 。

* link:concept-modes.html["瞭解 BlueXP 部署模式"]
* link:task-quick-start-standard-mode.html["以標準模式開始使用 BlueXP"]
* link:task-quick-start-restricted-mode.html["以受限模式開始使用 BlueXP"]
* link:task-quick-start-private-mode.html["以私有模式開始使用 BlueXP"]




== 權限

直接從 BlueXP 建立 Connector 需要特定權限、而 Connector 執行個體本身則需要另一組權限。如果您直接從 BlueXP 在 AWS 或 Azure 中建立 Connector 、則 BlueXP 會建立具有所需權限的 Connector 。

在標準模式下使用 BlueXP 時、您提供權限的方式取決於您規劃建立 Connector 的方式。

若要瞭解如何設定權限、請參閱下列內容：

* 標準模式
+
** link:concept-install-options-aws.html["AWS 中的連接器安裝選項"]
** link:concept-install-options-azure.html["Azure 中的連接器安裝選項"]
** link:concept-install-options-google.html["Google Cloud 中的 Connector 安裝選項"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["設定內部部署的雲端權限"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["設定受限模式的權限"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["設定私有模式的權限"]


若要檢視 Connector 日常作業所需的確切權限、請參閱下列頁面：

* link:reference-permissions-aws.html["瞭解Connector如何使用AWS權限"]
* link:reference-permissions-azure.html["瞭解Connector如何使用Azure權限"]
* link:reference-permissions-gcp.html["瞭解Connector如何使用Google Cloud權限"]


隨著後續版本中新增權限、您有責任更新 Connector 原則。如果需要新的權限、這些權限會列在版本資訊中。



== 連接器升級

NetApp 通常每個月都會更新 Connector 軟體，以引進新功能並改善穩定性。雖然 BlueXP  平台中的大部分服務和功能都是透過 SaaS 型軟體提供、但有幾項功能則取決於 Connector 的版本。其中包括Cloud Volumes ONTAP 支援內部的支援、ONTAP 內部的支援、叢集管理、設定及說明。

當您在標準模式或受限模式下使用 BlueXP 時、只要 Connector 有外送網際網路存取權來取得軟體更新、它就會自動將其軟體更新至最新版本。如果您在私有模式下使用 BlueXP 、則需要手動升級 Connector 。

link:task-upgrade-connector.html["瞭解如何在使用私有模式時手動升級 Connector 軟體"]。



== 作業系統與 VM 維護

在 Connector 主機上維護作業系統是您的責任。例如、您應該遵循公司的作業系統發佈標準程序、將安全性更新套用至 Connector 主機上的作業系統。

請注意、套用次要安全性更新時、不需要停止 Connector 主機上的任何服務。

如果您需要停止然後啟動 Connector VM 、您應該從雲端供應商的主控台或使用內部部署管理的標準程序來執行。

<<連接器必須隨時正常運作,請注意、 Connector 必須隨時都能運作>>。



== 多種工作環境與連接器

您可以使用相同的 Connector 來管理 BlueXP  中的多個工作環境。單一Connector應管理的工作環境數量上限各不相同。這取決於工作環境的類型、磁碟區數量、所管理的容量、以及使用者數量。

如果您有大規模部署、請與NetApp代表合作調整環境規模。

判斷您需要多少個 Connector 時，另一個考量是儲存設備所在的位置。例如，如果您的 Cloud Volumes ONTAP 同時位於 Google Cloud 和 Azure 中，則每個環境都需要一個 Connector 。如果您的儲存設備完全存在於內部部署，您可以在任何超大型擴充器或內部部署中執行 Connector 。

以下是其他範例：

* 您擁有多雲端環境（例如 AWS 和 Azure ）、偏好在 AWS 中安裝一個 Connector 、在 Azure 中安裝另一個 Connector 。每個系統都能管理 Cloud Volumes ONTAP 在這些環境中執行的不實系統。
* 服務供應商可能會使用一個 BlueXP  組織來為客戶提供服務、而使用另一個組織來為其中一個業務單位提供災難恢復。每個組織都會有個別的 Connector 。

