---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager 
summary: BlueXP讓IT專家和雲端架構設計師能夠使用NetApp的雲端解決方案、集中管理混合式多雲端基礎架構。 
---
= 深入瞭解BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP（前身為Cloud Manager）可讓IT專家和雲端架構設計師使用NetApp的雲端解決方案、集中管理混合式多雲端基礎架構。



== 功能

BlueXP是企業級SaaS型管理平台、無論資料位於何處、都能讓您隨時掌控資料。

* 設定與使用 https://cloud.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 實現跨雲端的高效率多重傳輸協定資料管理。
* 設定及使用雲端檔案儲存服務：
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["Amazon FSX for ONTAP Sf"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["適用於 Google Cloud Cloud Volumes Service"^]


* 探索與管理 https://bluexp.netapp.com/netapp-on-premises["內部部署儲存設備"^]
+
** E系列系統
** 叢集 ONTAP
** 系統StorageGRID


* 使用BlueXP的資料移動性、資料保護及資料分析與控制服務：
+
** https://bluexp.netapp.com/cloud-backup["雲端備份"^]
** https://bluexp.netapp.com/netapp-cloud-data-sense["雲端資料感測"^]
** https://bluexp.netapp.com/cloud-sync-service["Cloud Sync"^]
** https://bluexp.netapp.com/cloud-tiering["雲端分層"^]
** https://bluexp.netapp.com/digital-advisor["數位顧問"^]
** https://bluexp.netapp.com/global-file-cache["全域檔案快取"^]
** https://bluexp.netapp.com/k8s["Kubernetes"^]
** https://bluexp.netapp.com/ransomware-protection["勒索軟體保護"^]
** https://bluexp.netapp.com/replication["複寫"^]




https://cloud.netapp.com/cloud-manager["深入瞭解BlueXP"^]



== 支援的雲端供應商

BlueXP可讓您管理雲端儲存設備、並在Amazon Web Services、Microsoft Azure及Google Cloud中使用雲端服務。



== 成本

BlueXP的定價取決於您計畫使用的服務。 https://bluexp.netapp.com/pricing["瞭解BlueXP定價"^]。



== 藍圖的運作方式

BlueXP包含與BlueXP網站整合的SaaS型介面、以及可管理Cloud Volumes ONTAP 各種效益和其他雲端服務的Connectors。



=== 軟體即服務

可透過存取BlueXP https://console.bluexp.netapp.com["SaaS 型使用者介面"^] 和 API 。這項SaaS體驗可讓您在最新功能發佈時自動存取、並在NetApp帳戶和連接器之間輕鬆切換。


TIP: 如果您的作業環境無法存取傳出的網際網路、您可以在該環境中安裝Connector軟體、並存取Connector上的本機使用者介面。 link:concept-connectors.html["深入瞭解連接器"]。



=== BlueXP網站

https://cloud.netapp.com["BlueXP網站"^] 提供集中位置以供存取和管理 https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx["NetApp 雲端服務"^]。透過集中式使用者驗證、您可以使用相同的認證資料集來存取BlueXP和Cloud Insights 其他雲端服務、例如：



=== NetApp帳戶

首次登入BlueXP時、系統會提示您建立_NetApp帳戶_。此帳戶提供多租戶共享、可讓您在隔離的 _stap空間 _ 中組織使用者和資源。



=== 連接器

在大多數情況下、BlueXP帳戶管理員需要在雲端或內部部署網路中部署_Connector_。Connector讓BlueXP能夠管理公有雲環境中的資源和程序。

link:concept-connectors.html["深入瞭解何時需要連接器及其運作方式"]。



== SOC 2類型2認證

一家獨立認證的公共會計公司與服務稽核員、研究了BlueXP、Cloud Sync 整套技術、雲端分層、Cloud Data Sense和Cloud Backup（BlueXP平台）、並確認他們已根據適用的信任服務準則、達成SOC 2類報告。

https://www.netapp.com/company/trust-center/compliance/soc-2/["檢視NetApp的SOC 2報告"^]
