---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector 是指在雲端網路或內部部署網路中執行的 NetApp 軟體。它會執行 BlueXP 管理資料基礎架構所需執行的動作。Connector 會持續輪詢 BlueXP SaaS 層、以找出需要採取的任何行動。您不需要 Connector 即可開始使用 BlueXP 、但您需要建立 Connector 才能解除鎖定所有 BlueXP 功能和服務。 
---
= 瞭解 BlueXP  服務
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP 為您的組織提供單一控制面板、協助您在內部部署和雲端環境中建置、保護及管理資料。

您可以選擇是使用 BlueXP  SaaS 服務（標準模式），在受限的雲端環境中執行 BlueXP  （受限模式），還是在您自己的內部部署資料中心（私有模式）中安裝。無論您的環境為何，您都可以利用集中化管理和額外的資料服務，來維持儲存資源的健全性和安全性。

您選擇的模式會決定哪些服務可供您使用，以及您可以管理哪些儲存資源。

開始之前，請先比較每種模式所支援的不同儲存資源，以及可用的資料服務，以協助您判斷哪一項符合貴公司的需求。



== 資料服務

下表指出每個部署模式中可用的資料服務，您是否需要訂閱，以及何時需要支援帳戶。

[NOTE]
====
* 連接器 * 表格中的連接器欄會指出您何時需要標準模式的連接器。如果您在受限模式或私有模式下使用 BlueXP  ，則永遠需要有一個 Connector 。

====
[cols="24,19,19,19,19"]
|===
|  | 需要支援帳戶 | 需要 Connector | 需要訂閱 | 模式可用度 


| 警示 | 是的 | 是的 | 否 | 全部 


| 備份與還原 | 是的 | 是的 | 是的 | 標準，限制 


| 分類 | 是的 | 否 | 否 | 全部 


| 複製與同步 | 否 | 否 | 是的 |  


| 數位顧問 | 是的 | 否 | 否 | 全部 


| 數位錢包 | 是的 | 否* | 否 | 全部 


| 災難恢復 | 否 | 是的 | 是的 | 標準，限制 


| 經濟效益 | 是的 | 是的 | 否 |  


| 營運恢復能力 | 是的 | 是* | 否 |  


| 勒索軟體保護 | 否 | 是的 | 否 | 標準 


| 複寫 | 否 | 否* | 否 | 標準，限制 


| 軟體更新 | 是的 | 否 | 否 | 全部 


| 支援案例管理 | 是的 | 否 | 否 | 全部 


| 分層 | 否 | 否* | 是的 | 標準 


| Volume 快取 | 否 | 否 | 否 | 標準 
|===


== NetApp 儲存設備

您可以直接從 BlueXP  管理大部分的 NetApp 儲存資源，讓您可以從同一個應用程式檢視所有資源。

下表列出您可以從每個部署模式管理的儲存資源，以及您需要 Connector 或訂閱的儲存資源。

[NOTE]
====
* 連接器 * 表格中的連接器欄會指出您何時需要標準模式的連接器。如果您在受限模式或私有模式下使用 BlueXP  ，則永遠需要有一個 Connector 。

====
[cols="24,19,19,19,19"]
|===
|  | 需要支援帳戶 | 需要 Connector | 需要訂閱 | 模式可用度 


| Amazon FSX for NetApp ONTAP 產品 | 是的 | 否 ^1^ | 是的 | 標準 


| Amazon S3儲存設備 | 是的 | 否 | 是的 | 標準 


| Azure Blob 儲存設備 | 是的 | 否 | 否 | 標準 


| Azure NetApp Files | 否 | 否 ^2^ | 是的 | 標準，限制 


| Cloud Volumes ONTAP | 是的 | 是的 | 是的 | 標準，限制 


| 適用於 Google Cloud Cloud Volumes Service | 否 | 否 | 是的？ | 標準 


| E系列系統 | 否 | 是的 | 否 | 標準 


| Google Cloud Storage | 否 | 是的 | 是的？ | 標準 


| 內部部署 ONTAP 的叢集 | 是的 | 否 ^3^ | 否 | 全部 


| StorageGRID | 是的 | 是的 | 否 | 標準，限制 
|===
^1^ 某些動作需要連接器或 BlueXP  工作負載原廠連結。 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["瞭解哪些動作需要連接器或連結"^]

^2^ 雖然不需要連接器來設定和管理 Azure NetApp Files ，但如果您想要使用 BlueXP  分類來掃描 Azure NetApp Files 資料，則需要連接器。

^3^ 雖然直接探索內部部署 ONTAP 叢集不需要連接器，但如果您想要使用其他 BlueXP  功能，則需要連接器。 https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["深入瞭解內部ONTAP 部署的叢集探索與管理選項"^]
