---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXP 為您的組織提供單一控制面板、協助您在內部部署和雲端環境中建置、保護及管理資料。BlueXP SaaS 平台包含儲存與資料服務、可提供儲存管理、資料移動性、資料保護、以及資料分析與控制。管理功能是透過網路型主控台和 API 提供。 
---
= 深入瞭解BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP 為您的組織提供單一控制面板、協助您在內部部署和雲端環境中建置、保護及管理資料。BlueXP SaaS 平台包含儲存與資料服務、可提供儲存管理、資料移動性、資料保護、以及資料分析與控制。管理功能是透過網路型主控台和 API 提供。



== 功能

BlueXP 平台提供四大資料管理支柱：儲存、行動力、保護、分析與控制。

儲存設備:: 探索、部署及管理儲存設備、無論是在 AWS 、 Azure 、 Google Cloud 或內部部署。
+
--
* 設定與使用 https://["Cloud Volumes ONTAP"^] 實現跨雲端的高效率多重傳輸協定資料管理。
* 設定及使用雲端檔案儲存服務：
+
** https://["Azure NetApp Files"^]
** https://["Amazon FSX for ONTAP Sf"^]
** https://["適用於 Google Cloud Cloud Volumes Service"^]


* 探索與管理 https://["內部部署儲存設備"^]：
+
** E系列系統
** 叢集 ONTAP
** 系統StorageGRID


* 協調與保護 https://["Kubernetes 持續資料"^]


--
行動力:: 透過同步、複製、分層及快取資料、將資料移至所需的位置。
+
--
* https://["複製與同步"^]
* https://["邊緣快取"^]
* https://["分層"^]


--
保護:: 使用自動化保護機制來保護資料、避免資料遺失、非計畫性中斷、勒索軟體及其他網路威脅。
+
--
* https://["備份與還原"^]
* https://["複寫"^]


--
分析與控制:: 使用工具來監控、對應及最佳化您的資料儲存與基礎架構。
+
--
* https://["分類"^]
* https://["數位顧問"^]
* https://["勒索軟體保護"^]


--


https://["深入瞭解如何使用 BlueXP 協助貴組織"^]



== 支援的雲端供應商

BlueXP可讓您管理雲端儲存設備、並在Amazon Web Services、Microsoft Azure及Google Cloud中使用雲端服務。



== 成本

BlueXP的定價取決於您計畫使用的服務。 https://["瞭解BlueXP定價"^]



== 藍圖的運作方式

BlueXP 包括透過 SaaS 層提供的網路型主控台、提供多租戶服務的帳戶、以及管理 Cloud Volumes ONTAP 和其他雲端服務的 Connectors 。



=== 軟體即服務

可透過存取BlueXP https://["網路型主控台"^] 和 API 。這項 SaaS 體驗可讓您在推出時自動存取最新功能、並在 BlueXP 帳戶和 Connector 之間輕鬆切換。



=== BlueXP帳戶

第一次登入 BlueXP 時、系統會提示您建立 _BlueXP 帳戶 _ 。此帳戶提供多租戶共享、可讓您在隔離的 _stap空間 _ 中組織使用者和資源。

link:concept-netapp-accounts.html["深入瞭解客戶"]。



=== 連接器

您不需要 Connector 即可開始使用 BlueXP 、但您需要建立 Connector 才能解除鎖定所有 BlueXP 功能和服務。Connector 可在內部部署和雲端環境中管理資源和程序。需要使用 Cloud Volumes ONTAP 和其他資料服務。

link:concept-connectors.html["深入瞭解連接器"]。



=== 受限模式和私有模式

在安全性和連線能力受限的環境中、也支援 BlueXP 。您可以使用 _limit modity_ 或 _private modity_ 來限制與 BlueXP SaaS 層的輸出連線。

link:concept-modes.html["深入瞭解 BlueXP 部署模式"]。



== SOC 2類型2認證

一家專業的執業會計師公司和服務稽核員審查了 BlueXP 、並確認它根據適用的信託服務標準、達成 SOC 2 類報告。

https://["檢視NetApp的SOC 2報告"^]
