---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXP 為您的組織提供單一控制面板、協助您在內部部署和雲端環境中建置、保護及管理資料。BlueXP SaaS 平台包括提供儲存管理、資料移動性、資料保護、以及資料分析與控制的服務。管理功能是透過網路型主控台和 API 提供。 
---
= 深入瞭解BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP 為您的組織提供單一控制面板、協助您在內部部署和雲端環境中建置、保護及管理資料。BlueXP SaaS 平台包括提供儲存管理、資料移動性、資料保護、以及資料分析與控制的服務。管理功能是透過網路型主控台和 API 提供。



== 功能

BlueXP 平台提供四大資料管理支柱：儲存、行動力、保護、分析與控制。

儲存設備:: 探索、部署及管理儲存設備、無論是在 AWS 、 Azure 、 Google Cloud 或內部部署中。
+
--
* 設定及使用雲端檔案儲存服務：
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["Amazon FSX for NetApp ONTAP 產品"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["適用於 Google Cloud Cloud Volumes Service"^]


* 設定與使用 https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 實現跨雲端的高效率多重傳輸協定資料管理。
* 探索與管理 https://bluexp.netapp.com/netapp-on-premises["內部部署儲存設備"^]：
+
** E系列系統
** 叢集 ONTAP
** 系統StorageGRID




--
行動力:: 透過同步、複製及分層資料、將資料移至需要的位置。
+
--
* https://bluexp.netapp.com/cloud-sync-service["複製與同步"^]
* https://bluexp.netapp.com/cloud-tiering["分層"^]


--
保護:: 使用自動化保護機制來保護資料、避免資料遺失、非計畫性中斷、勒索軟體及其他網路威脅。
+
--
* https://bluexp.netapp.com/cloud-backup["備份與還原"^]
* https://bluexp.netapp.com/disaster-recovery["災難恢復"^]
* https://bluexp.netapp.com/replication["複寫"^]
* https://bluexp.netapp.com/ransomware-protection["勒索軟體保護"^]


--
分析與控制:: 使用工具來監控、對應及最佳化您的資料儲存與基礎架構。取得可據以行動的情報、以最佳化儲存健全狀況、恢復能力和經濟效益。
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["分類"^]
* https://bluexp.netapp.com/digital-advisor["數位顧問"^]
* https://bluexp.netapp.com/digital-advisor["經濟效益"^]
* https://bluexp.netapp.com/digital-advisor["營運恢復能力"^]


--


https://bluexp.netapp.com/["深入瞭解如何使用 BlueXP  來管理混合式多雲端環境中的資料"^]



== 支援的雲端供應商

BlueXP可讓您管理雲端儲存設備、並在Amazon Web Services、Microsoft Azure及Google Cloud中使用雲端服務。



== 成本

BlueXP的定價取決於您計畫使用的服務。 https://bluexp.netapp.com/pricing["瞭解BlueXP定價"^]



== 藍圖的運作方式

BlueXP  包含透過 SaaS 層提供的網路型主控台、資源與存取管理系統、以及可管理工作環境並啟用 BlueXP  雲端服務的 Connectors 。



=== 軟體即服務

BlueXP  可透過和 API 存取 https://console.bluexp.netapp.com["網路型主控台"^]。這項 SaaS 體驗可讓您在發行時自動存取最新功能、並在 BlueXP  組織、專案和連接器之間輕鬆切換。



=== BlueXP  身分識別與存取管理（ IAM ）

BlueXP  身分識別與存取管理（ IAM ）是一種資源與存取管理模式、可提供精細的資源與權限管理：

* 頂層組織 _ 可讓您管理各種專案的存取權
* _Folders_ 可讓您將相關專案分組在一起
* 資源管理可讓您將資源與一或多個資料夾或專案建立關聯
* 存取管理可讓您將角色指派給組織階層不同層級的成員


在標準模式下使用 BlueXP  時、支援 BlueXP  IAM 。如果您是以受限模式或私人模式使用 BlueXP  、則會使用 BlueXP  _account_ 來管理工作區、使用者和資源。

* link:concept-identity-and-access-management.html["深入瞭解 BlueXP  IAM"]
* link:concept-netapp-accounts.html["瞭解 BlueXP 帳戶"]




=== 連接器

您不需要 Connector 即可開始使用 BlueXP 、但您需要建立 Connector 才能解除鎖定所有 BlueXP 功能和服務。Connector 可在內部部署和雲端環境中管理資源和程序。需要管理工作環境（例如 Cloud Volumes ONTAP ）、並使用許多 BlueXP  服務。

link:concept-connectors.html["深入瞭解連接器"]。



=== 部署模式

BlueXP  在安全性和連線能力受限的環境中受到支援。您可以使用 _limit modity_ 或 _private modity_ 來限制與 BlueXP SaaS 層的輸出連線。

link:concept-modes.html["深入瞭解 BlueXP 部署模式"]。



== SOC 2類型2認證

一家專業的執業會計師公司和服務稽核員審查了 BlueXP 、並確認它根據適用的信託服務標準、達成 SOC 2 類報告。

https://www.netapp.com/company/trust-center/compliance/soc-2/["檢視NetApp的SOC 2報告"^]
