---
settings:
  name: BlueXP setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: BlueXP  設定與管理
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 已知限制
      url: "/reference-limitations.html"
    - title: 支援的 Linux 作業系統變更
      url: "/reference-connector-operating-system-changes.html"
  - title: 開始使用
    entries:
    - title: 瞭解基礎知識
      entries:
      - title: 藍圖
        url: "/concept-overview.html"
      - title: 連接器
        url: "/concept-connectors.html"
      - title: 部署模式
        url: "/concept-modes.html"
    - title: 開始使用標準模式
      entries:
      - title: 快速入門工作流程
        url: "/task-quick-start-standard-mode.html"
      - title: 為 BlueXP  主控台準備網路
        url: "/reference-networking-saas-console.html"
      - title: 註冊BlueXP
        url: "/task-sign-up-saas.html"
      - title: 建立連接器
        entries:
        - title: AWS
          entries:
          - title: 連接器安裝選項
            url: "/concept-install-options-aws.html"
          - title: 從BlueXP建立連接器
            url: "/task-install-connector-aws-bluexp.html"
          - title: 從市場建立 Connector
            url: "/task-install-connector-aws-marketplace.html"
          - title: 手動安裝 Connector
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: 連接器安裝選項
            url: "/concept-install-options-azure.html"
          - title: 從BlueXP建立連接器
            url: "/task-install-connector-azure-bluexp.html"
          - title: 從市場建立 Connector
            url: "/task-install-connector-azure-marketplace.html"
          - title: 手動安裝 Connector
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: 連接器安裝選項
            url: "/concept-install-options-google.html"
          - title: 從 BlueXP 或 gCloud 建立 Connector
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: 手動安裝 Connector
            url: "/task-install-connector-google-manual.html"
        - title: 內部部署
          url: "/task-install-connector-on-prem.html"
      - title: 訂閱 NetApp 智慧服務
        url: "/task-subscribe-standard-mode.html"
      - title: 接下來您可以做什麼
        url: "/reference-whats-next.html"
    - title: 開始使用受限模式
      entries:
      - title: 快速入門工作流程
        url: "/task-quick-start-restricted-mode.html"
      - title: 準備部署
        url: "/task-prepare-restricted-mode.html"
      - title: 部署 Connector
        url: "/task-install-restricted-mode.html"
      - title: 訂閱 NetApp 智慧服務
        url: "/task-subscribe-restricted-mode.html"
      - title: 接下來您可以做什麼
        url: "/reference-whats-next-restricted-mode.html"
    - title: 開始使用私有模式
      entries:
      - title: 快速入門工作流程
        url: "/task-quick-start-private-mode.html"
      - title: 準備部署
        url: "/task-prepare-private-mode.html"
      - title: 部署 Connector
        url: "/task-install-private-mode.html"
      - title: BlueXP 帳戶
        entries:
        - title: 深入瞭解客戶
          url: "/concept-netapp-accounts.html"
        - title: 管理 BlueXP 帳戶
          url: "/task-managing-netapp-accounts.html"
      - title: 接下來您可以做什麼
        url: "/reference-whats-next-private-mode.html"
  - title: 使用 BlueXP
    entries:
    - title: 登入BlueXP
      url: "/task-logging-in.html"
    - title: 管理您的 BlueXP 用戶設定
      url: "/task-user-settings.html"
  - title: 管理BlueXP
    entries:
    - title: 身分識別與存取管理
      entries:
      - title: 瞭解 BlueXP  IAM
        url: "/concept-identity-and-access-management.html"
      - title: BlueXP  IAM 入門
        url: "/task-iam-get-started.html"
      - title: 使用資料夾和專案來組織資源
        url: "/task-iam-manage-folders-projects.html"
      - title: 管理會員和服務帳戶
        url: "/task-iam-manage-members-permissions.html"
      - title: 使用角色來控制成員存取資源的權限
        url: "/task-iam-manage-roles.html"
      - title: 管理資源階層
        url: "/task-iam-manage-resources.html"
      - title: 將 Connector 與其他資料夾和專案建立關聯
        url: "/task-iam-associate-connectors.html"
      - title: 在組織、專案和連接器之間切換
        url: "/task-iam-switch-organizations-projects.html"
      - title: 組織和專案 ID
        url: "/task-iam-rename-organization.html"
      - title: 監控或稽核 IAM 活動
        url: "/task-iam-audit-actions-timeline.html"
      - title: BlueXP  存取角色
        entries:
        - title: 瞭解 BlueXP  存取角色
          url: "/reference-iam-predefined-roles.html"
        - title: 平台角色
          url: "/reference-iam-platform-roles.html"
        - title: 應用程式角色
          entries:
          - title: Keystone 角色
            url: "/reference-iam-keystone-roles.html"
          - title: 儲存角色
            url: "/reference-iam-storage.roles.html"
        - title: 資料服務角色
          entries:
          - title: 勒索軟體保護角色
            url: "/reference-iam-ransomware-roles.html"
    - title: BlueXP  帳戶（僅限私人模式）
      entries:
      - title: 深入瞭解客戶
        url: "/concept-netapp-accounts.html"
      - title: 管理 BlueXP 帳戶
        url: "/task-managing-netapp-accounts.html"
    - title: 身分識別聯盟
      url: "/concept-federation.html"
    - title: 連接器
      entries:
      - title: 維護 VM 和 OS
        url: "/task-maintain-connectors.html"
      - title: 安裝 CA 簽署的憑證以進行 Web 主控台存取
        url: "/task-installing-https-cert.html"
      - title: 設定連接器以使用Proxy伺服器
        url: "/task-configuring-proxy.html"
      - title: 需要在 EC2 執行個體上使用 IMDSv2
        url: "/task-require-imdsv2.html"
      - title: 管理連接器升級
        url: "/task-upgrade-connector.html"
      - title: 使用多個連接器
        url: "/task-manage-multiple-connectors.html"
      - title: 疑難排解 Connector
        url: "/task-troubleshoot-connector.html"
      - title: 解除安裝並移除 Connector
        url: "/task-uninstall-connector.html"
      - title: 預設組態
        url: "/reference-connector-default-config.html"
      - title: 在 BlueXP  中強制執行 ONTAP 權限
        url: "/task-ontap-access-connector.html"
    - title: 認證與訂閱
      entries:
      - title: AWS
        entries:
        - title: 瞭解認證和權限
          url: "/concept-accounts-aws.html"
        - title: 管理認證與訂閱
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: 瞭解認證和權限
          url: "/concept-accounts-azure.html"
        - title: 管理認證與訂閱
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: 瞭解專案和權限
          url: "/concept-accounts-gcp.html"
        - title: 管理認證與訂閱
          url: "/task-adding-gcp-accounts.html"
      - title: 管理與 BlueXP  組織或帳戶相關的 NSS 認證
        url: "/task-adding-nss-accounts.html"
      - title: 管理與您的BlueXP登入相關的認證資料
        url: "/task-manage-user-credentials.html"
    - title: 監控 BlueXP  作業
      url: "/task-monitor-cm-operations.html"
  - title: 參考資料
    entries:
    - title: 權限
      entries:
      - title: 權限摘要
        url: "/reference-permissions.html"
      - title: Connector的AWS權限
        url: "/reference-permissions-aws.html"
      - title: 連接器的Azure權限
        url: "/reference-permissions-azure.html"
      - title: Connector的Google Cloud權限
        url: "/reference-permissions-gcp.html"
    - title: 連接埠
      entries:
      - title: AWS 中的 Connector 安全性群組規則
        url: "/reference-ports-aws.html"
      - title: Azure 中的 Connector 安全性群組規則
        url: "/reference-ports-azure.html"
      - title: Google Cloud 中的連接器防火牆規則
        url: "/reference-ports-gcp.html"
      - title: on-premisesConnector 的端口
        url: "/reference-ports-on-prem.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/task-support-registration.html"
    - title: 取得協助
      url: "/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
