---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, httpstokens 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。

這些限制僅適用於 BlueXP  的設定與管理： Connector 、軟體即服務（ SaaS ）平台等。



== 連接器限制



=== 不支援透明 Proxy 伺服器

BlueXP 不支援使用 Connector 的透明 Proxy 伺服器。

link:task-configuring-proxy.html["深入瞭解如何搭配 Connector 使用 Proxy 伺服器"]。



=== 可能與172範圍內的IP位址發生衝突

BlueXP部署連接器時、會有兩個介面、其中IP位址介於172.17.0.0/16和172.18.0.0/16範圍內。

如果您的網路已設定具有上述任一範圍的子網路、則可能會遇到來自BlueXP的連線故障。例如ONTAP 、在BlueXP中探索內部的功能不全的叢集可能會失敗。

請參閱知識庫文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["BlueXP Connector IP與現有網路衝突"] 如需如何變更連接器介面的IP位址的指示。



=== 不支援SSL解密

BlueXP不支援啟用SSL解密的防火牆組態。如果啟用SSL解密、則錯誤訊息會顯示在BlueXP中、而Connector執行個體則顯示為非作用中。

為了增強安全性、您可以選擇 link:task-installing-https-cert.html["安裝由憑證授權單位（CA）簽署的HTTPS憑證"]。



=== 載入本機UI時顯示空白頁面

如果您載入在 Connector 上執行的 Web 型主控台、介面可能會有時無法顯示、只會出現空白頁面。

此問題與快取問題有關。因應措施是使用無痕式或私有網路瀏覽器工作階段。



=== 不支援共享 Linux 主機

與其他應用程式共用的VM不支援Connector。VM必須專用於Connector軟體。



=== 第三方代理程式與擴充功能

Connector VM不支援協力廠商代理程式或VM擴充。
