---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 開始使用 BlueXP 時、請確定您的網路允許從 BlueXP 主控台存取特定端點。視您打算如何使用 BlueXP 而定、您可能也需要為 Connector 和特定 BlueXP 服務設定網路。 
---
= 準備好您的網路
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
開始使用 BlueXP 時、請確定您的網路允許從 BlueXP 主控台存取特定端點。視您打算如何使用 BlueXP 而定、您可能也需要為 Connector 和特定 BlueXP 服務設定網路。



== 準備網路以供使用者存取 BlueXP 主控台

當您使用透過 SaaS 層提供的 BlueXP 網路型主控台時、它會與多個端點聯絡、以完成資料管理工作。執行 Web 瀏覽器的機器必須連線至這些端點。

[cols="2*"]
|===
| 端點 | 目的 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | 當您使用 BlueXP 網路型主控台時、您的網路瀏覽器會連絡這些 URL 。 


 a| 
AWS 服務（ amazonaws.com):

* CloudForation
* 彈性運算雲端（ EC2 ）
* 金鑰管理服務（ KMS ）
* 安全性權杖服務（ STOS ）
* 簡易儲存服務（ S3 ）

| 需要在AWS中部署從BlueXP部署連接器。確切的端點取決於部署Connector的區域。 https://docs.aws.amazon.com/general/latest/gr/rande.html["如需詳細資料、請參閱 AWS 文件。"^] 


| \https://management.azure.com

\https://login.microsoftonline.com | 在大多數Azure地區中部署來自BlueXP的Connector。 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | 需要在Azure Germany地區部署來自BlueXP的Connector。 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | 需要在Azure US Gov地區部署來自BlueXP的Connector。 


| \https://www.googleapis.com | 需要在Google Cloud中部署來自BlueXP的Connector。 


| \https://signin.b2c.netapp.com | 需要更新NetApp 支援網站 驗證（NSS）認證或新增新的NSS認證至BlueXP。 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | 您的網頁瀏覽器會連線至這些端點、以便透過BlueXP進行集中式使用者驗證。 


| \https://widget.intercom.io | 產品內對談可讓您與 NetApp 雲端專家交談。 
|===
除了這些端點之外、您還需要確保 Connector 具備對外網際網路存取權、以便聯絡特定端點、以進行日常作業。您可以依照下一節中的連結、找到這些端點的清單。



== 準備連接器的網路連線

您如何為 Connector 準備網路、取決於您打算在雲端或內部部署安裝 Connector 的位置。如需 Connector 網路連線需求的詳細資訊、請參閱下列頁面：

* link:task-set-up-networking-aws.html["設定 AWS 網路"]
* link:task-set-up-networking-azure.html["設定 Azure 網路"]
* link:task-set-up-networking-google.html["設定 Google Cloud 網路"]
* link:task-set-up-networking-on-prem.html["設定內部網路"]




== 為 BlueXP 服務做好網路準備

開始使用 BlueXP 時、您應確保已符合您計畫使用的 BlueXP 服務的網路需求。如需詳細資訊、請參閱每項服務的文件。

https://docs.netapp.com/us-en/bluexp-family/["BlueXP文件"^]
