---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  身分識別與存取管理包含數個預先定義的角色、您可以指派給組織成員。 
---
= BlueXP  平台存取角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
平台角色是您可以指派給使用者的最廣泛角色，並允許 BlueXP 管理的所有權限，包括指派角色和新增使用者。擁有平台角色的使用者可存取 BlueXP  中的所有資料服務和應用程式。BlueXP  包括兩個平台角色： * 組織管理 * 和 * 資料夾或專案管理 * 。兩個 BlueXP  平台角色的主要差異在於角色的適用範圍。

.大型跨國組織在 BlueXP  中扮演組織角色的範例
XYZ Corporation 是一家跨國企業，其目標是根據北美，歐洲和亞太地區等地理區域，將資料儲存資源的存取區隔開來。他們希望每個區域都能完全掌控自己的資源，同時維持集中監督。

為達成此目標，在 XYZ 公司的 BlueXP  中指派 * 組織管理員 * 角色的人員會建立初始工作環境，然後在 BlueXP  中為每個區域建立個別的資料夾。每個區域的資料夾都包含與該區域相關的專案（含相關資源）。* 組織管理 * 會在每個個別地區指派 * 資料夾或專案管理 * 角色給 BlueXP  使用者。

初始設定完成後，具有 * 資料夾或專案管理員 * 角色的區域管理員可以建立新的工作環境，並在其區域內新增使用者。這些區域管理員也可以新增 / 移除 / 重新命名指派給他們的資料夾和專案。* 組織管理員 * 繼承任何新工作環境或資源的權限，維持整個組織的儲存使用率可見度。

下表指出每個 BlueXP  平台角色可以執行的動作。

[cols="2,1,1"]
|===
| 工作 | 組織管理員 | 資料夾或專案管理員 


| 建立連接器 | 是的 | 否 


| 建立，修改或刪除工作環境（使用 BlueXP  畫布新增或探索新資源） | 是的 | 是的 


| 建立資料夾和專案，包括刪除 | 是的 | 否 


| 重新命名現有資料夾和專案 | 是的 | 是的 


| 指派角色並新增使用者 | 是的 | 是的 


| 將資源與資料夾和專案建立關聯 | 是的 | 是的 


| 將 Connectors 與資料夾和專案建立關聯 | 是的 | 否 


| 從資料夾和專案中移除連接器 | 是的 | 否 


| 管理連接器（編輯憑證，設定等） | 是的 | 否 


| 從「設定」 > 「認證」管理認證 | 是的 | 是的 


| 檢視 BlueXP  時間表 | 是的 | 是的 


| 使用 BlueXP  服務 | 是的 | 是的 


| 註冊 BlueXP  以取得支援並提交案例 | 是的 | 是的 
|===