---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: 為使用者指派平台角色，以授予管理BlueXP、指派角色、新增使用者、建立連接器和管理聯合的權限。 
---
= BlueXP  平台存取角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
為使用者指派平台角色，以授予管理BlueXP、指派角色、新增使用者、建立連接器和管理聯合的權限。

.大型跨國組織在 BlueXP  中扮演組織角色的範例
XYZ 公司按地區（北美、歐洲和亞太地區）組織資料儲存訪問，從而提供區域控制和集中監督。

XYZ 公司的BlueXP中的 *組織管理員* 為每個區域建立一個初始組織和單獨的資料夾。每個區域的*資料夾或專案管理員*在該區域的資料夾中組織專案（及相關資源）。

具有「資料夾或專案管理員」角色的區域管理員透過新增資源和使用者來主動管理他們的資料夾。這些區域管理員還可以新增、刪除或重新命名他們管理的資料夾和項目。  *組織管理員*繼承任何新資源的權限，保持整個組織的儲存使用情況的可見性。

在同一個組織內，一名使用者被指派了*共同管理員*角色來管理該組織與其企業 IdP 的聯合。該使用者可以新增或刪除聯合組織，但不能管理組織內的使用者或資源。  *組織管理員*為使用者指派*共同檢視者*角色，以檢查聯合狀態並查看聯合組織。

下表列出了每個BlueXP平台角色可以執行的動作。



== 組織管理角色

[cols="2,1,1"]
|===
| 工作 | 組織管理員 | 資料夾或專案管理員 


| 建立連接器 | 是的 | 否 


| 建立，修改或刪除工作環境（使用 BlueXP  畫布新增或探索新資源） | 是的 | 是的 


| 建立資料夾和專案，包括刪除 | 是的 | 否 


| 重新命名現有資料夾和專案 | 是的 | 是的 


| 指派角色並新增使用者 | 是的 | 是的 


| 將資源與資料夾和專案建立關聯 | 是的 | 是的 


| 將 Connectors 與資料夾和專案建立關聯 | 是的 | 否 


| 從資料夾和專案中移除連接器 | 是的 | 否 


| 管理連接器（編輯憑證，設定等） | 是的 | 否 


| 從「設定」 > 「認證」管理認證 | 是的 | 是的 


| 建立、管理和檢視聯合 | 是的 | 否 


| 透過BlueXP註冊支援並提交案例 | 是的 | 是的 


| 使用數據服務 | 是的 | 是的 


| 查看BlueXP時間軸和通知 | 是的 | 是的 
|===


== 聯盟角色

[cols="2,1,1"]
|===
| 工作 | 聯盟管理員 | 聯合查看器 


| 創建聯盟 | 是的 | 否 


| 驗證域名 | 是的 | 否 


| 將網域新增至聯合 | 是的 | 否 


| 禁用和刪除聯盟 | 是的 | 否 


| 測驗聯盟 | 是的 | 否 


| 查看聯盟及其詳細信息 | 是的 | 是的 
|===