---
sidebar: sidebar 
permalink: reference-connector-default-config.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux 
summary: 如果您需要疑難排解 Connector 、可能有助於瞭解其設定方式。 
---
= Connector 的預設組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可能想要在部署連接器之前、或是需要疑難排解任何問題時、先深入瞭解連接器。



== 具備網際網路存取的預設組態

如果您是從BlueXP、雲端供應商的市場部署Connector、或是手動將Connector安裝在可存取網際網路的內部部署Linux主機上、則適用下列組態詳細資料。



=== AWS詳細資料

如果您是從BlueXP或雲端供應商的市場部署Connector、請注意下列事項：

* EC2執行個體類型為T3.xLarge。
* 映像的作業系統為Red Hat Enterprise Linux 7.6（HVM）。
+
作業系統不含 GUI 。您必須使用終端機來存取系統。

* EC2 Linux執行個體的使用者名稱為EC2使用者。
* 預設的系統磁碟為100 GiB gp2磁碟。




=== Azure詳細資料

如果您是從BlueXP或雲端供應商的市場部署Connector、請注意下列事項：

* VM類型為DS3 v2。
* 映像的作業系統為CentOS 7.6。
+
作業系統不含 GUI 。您必須使用終端機來存取系統。

* 預設系統磁碟為100 GiB優質SSD磁碟。




=== Google Cloud詳細資料

如果您是從BlueXP或雲端供應商的市場部署Connector、請注意下列事項：

* VM執行個體為n2-Standard-4。
* 映像的作業系統為Red Hat Enterprise Linux 8.6.
+
作業系統不含 GUI 。您必須使用終端機來存取系統。

* 預設系統磁碟為100 GiB SSD持續磁碟。




=== 安裝資料夾

Connector 安裝資料夾位於下列位置：

/opt/application/NetApp/cloudmanager



=== 記錄檔

記錄檔包含在下列資料夾中：

* /opp/application/NetApp/cloudmanager/log
+
此資料夾中的記錄提供有關Connector和Docker影像的詳細資料。

* /opp/application/netapp/cloudmanager/dock_occm/data/log
+
此資料夾中的記錄提供有關在Connector上執行雲端服務和BlueXP服務的詳細資料。





=== 連接器服務

* BlueXP服務的名稱為occm。
* occm 服務取決於 MySQL 服務。
+
如果 MySQL 服務當機、則 occm 服務也會停機。





=== 套件

如果尚未安裝下列套件、則BlueXP會在Linux主機上安裝：

* 7Zip
* AWSCLI
* Docker
* Java
* Kubecl
* MySQL
* Tridentctl
* 拉出
* WGet




=== 連接埠

連接器在 Linux 主機上使用下列連接埠：

* 80 （用於 HTTP 存取）
* 用於 HTTPS 存取的 443
* 適用於BlueXP資料庫的3306
* 8080 for the BlueXP API Proxy
* 8666 、適用於 Service Manager API
* 8777 、適用於 Health 檢查器 Container Service API




== 預設組態、不含網際網路存取

如果您手動將Connector安裝在無法存取網際網路的內部部署Linux主機上、則適用下列組態。 link:task-install-connector-onprem-no-internet.html["深入瞭解此安裝選項"]。

* Connector 安裝資料夾位於下列位置：
+
/opt/application/NetApp/DS

* 記錄檔包含在下列資料夾中：
+
/var/lib/dock/volages/ds_occmdata/log

+
此資料夾中的記錄提供有關Connector和Docker影像的詳細資料。

* 所有服務都在Docker容器內執行
+
這些服務取決於執行的Docker執行時間服務

* 連接器在 Linux 主機上使用下列連接埠：
+
** 80 （用於 HTTP 存取）
** 用於 HTTPS 存取的 443



