---
sidebar: sidebar 
permalink: reference-permissions-gcp.html 
keywords: permissions, gcp, gcp permissions 
summary: BlueXP需要權限才能在雲端供應商中執行動作。這些權限包含在 NetApp 提供的原則中。您可能想要瞭解BlueXP使用這些權限的功能。 
---
= Connector的Google Cloud權限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP需要權限才能在Google Cloud中執行動作。這些權限包含在NetApp提供的自訂角色中。您可能想要瞭解BlueXP使用這些權限的功能。



== 服務帳戶權限

下方顯示的自訂角色提供Connector在Google Cloud網路中管理資源和程序所需的權限。

您必須將此自訂角色套用至連接器VM的服務帳戶。

* link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["設定標準模式的 Google Cloud 權限"]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["設定受限模式的權限"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["設定私有模式的權限"]


您也必須確保在後續版本中新增權限時、該角色是最新的。如果需要新的權限、這些權限會列在版本資訊中。

[source, yaml]
----
title: NetApp BlueXP
description: Permissions for the service account associated with the Connector instance.
stage: GA
includedPermissions:
- iam.serviceAccounts.actAs
- compute.regionBackendServices.create
- compute.regionBackendServices.get
- compute.regionBackendServices.list
- compute.networks.updatePolicy
- compute.backendServices.create
- compute.addresses.list
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.addAccessConfig
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.delete
- compute.instances.detachDisk
- compute.instances.get
- compute.instances.getSerialPortOutput
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice
- compute.instanceGroups.get
- compute.addresses.get
- compute.instances.updateNetworkInterface
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.list
- compute.snapshots.setLabels
- compute.subnetworks.get
- compute.subnetworks.list
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- compute.instances.setServiceAccount
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- logging.logEntries.list
- logging.privateLogEntries.list
- resourcemanager.projects.get
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.list
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
- storage.buckets.update
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- storage.objects.get
- storage.objects.list
- monitoring.timeSeries.list
- storage.buckets.getIamPolicy
- cloudkms.cryptoKeys.getIamPolicy
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keyRings.get
- cloudkms.keyRings.getIamPolicy
- cloudkms.keyRings.setIamPolicy
----


== 如何使用Google Cloud權限

[cols="50,50"]
|===
| 行動 | 目的 


| -compute 、 disks.create
- compute 。 disks.createSnapshot
- compute.disks.delete
- compute 、 disks.get
-compute 、 disks.list
- compute.disks.setLabels
- compute.disks.use | 建立及管理 Cloud Volumes ONTAP 磁碟以供使用。 


| -compute 、防火牆、 create
- compute.firewalls.delete
- compute 、防火牆、 Get
-compute 、防火牆。 list | 建立 Cloud Volumes ONTAP 防火牆規則以供使用。 


| 運算： globalOperations 。 Get | 以取得作業狀態。 


| - compute 、 images.get
- compile.images.getFromFamily
- compute 。 images.list
- compute.images.useReadOnly | 取得 VM 執行個體的映像。 


| - compute.instances.attachDisk
- compute.instances.detachDisk | 可將磁碟安裝到 Cloud Volumes ONTAP 實體上、並將其拆離。 


| - compute.instances.create
- compute.instances.delete | 建立及刪除 Cloud Volumes ONTAP 不顯示的 VM 執行個體。 


| - compute.instances.get | 列出 VM 執行個體。 


| - compute.instances.getSerialPortOutput | 以取得主控台記錄。 


| - compute.instances.list | 可檢索區域中的實例列表。 


| - compute.instances.setDeletionProtection | 設定執行個體的刪除保護。 


| - compute.instances.setLabels | 以新增標籤。 


| - compute.instances.setMachineType
- compute.instances.setMinCpuPlatform | 變更 Cloud Volumes ONTAP 機器類型以供使用。 


| - compute.instances.setMetadata | 新增中繼資料。 


| - compute.instances.setTags | 新增防火牆規則的標記。 


| - compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice | 開始和停止 Cloud Volumes ONTAP 功能。 


| - compute 。 machineTypes 。 Get | 取得要檢查 qoutas 的核心數量。 


| - compute.projects.get | 支援多個專案。 


| - compute 、 snapshots.create
- compute.snapshots.delete
- compute 、 snapshots.get
-compute 、 snapshots.list
- compute.snapshots.setLabels | 以建立及管理持續磁碟快照。 


| - compute.networks.get
- compute.networks.list
- compute 、 regions 、 get
- compute 。 regions 。 list
- compute 。 subnets.get
-compute 。 subnets.list
- competing.zoneOperations 。 GET
- compute 、 zones 、 get
- compute 。 sites.list | 取得建立全新 Cloud Volumes ONTAP 的物件虛擬機器執行個體所需的網路資訊。 


| - deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.inits.get
- deploymentmanager.lists.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.edes.get
- deploymentmanager.edes.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list | 使用 Cloud Volumes ONTAP Google Cloud Deployment Manager 部署物件虛擬機器執行個體。 


| - logging.logEntries 清單
- logging.privateLogEntries 清單 | 以取得堆疊記錄磁碟機。 


| - resourcemanager.projects.get | 支援多個專案。 


| - storage 。 buckets 。 create
- storage.buckets.delete
- 儲存、貯體、取得
- storage 。 buckets 。 list
- storage 。 buckets 。 update | 建立及管理 Google Cloud Storage 儲存庫以進行資料分層。 


| - cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyclings 。 list | 搭配 Cloud Volumes ONTAP 使用 Cloud Key Management Service 的客戶管理加密金鑰。 


| - compute.instances.setServiceAccount
- iam.serviceAccounts.actAs
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
儲存、物件、 GET
儲存、物件、清單 | 在 Cloud Volumes ONTAP 整個過程中設定服務帳戶。此服務帳戶提供資料分層至 Google Cloud Storage 儲存庫的權限。 


| 運算.addresses.list | 在部署HA配對時擷取區域中的位址。 


| - compute 。 backendServices.create
- compute 。 RegionBackendServices.create
- compute 、 Region.BackendServices.get
-compute 。 RegionBackendServices.list | 設定後端服務以在HA配對中分配流量。 


| - compute.networks.updatePolicy | 將防火牆規則套用至HA配對的VPC和子網路。 


| - compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.instances.addAccessConfig | 以啟用 BlueXP 分類。 


| - compute.instanceGroups.get
- compute 、 addresses.get
- compute.instances.updateNetworkInterface | 在Cloud Volumes ONTAP 以各種方式建立及管理儲存VM的整組。 


| -monitoring.timeSeries.list
- storage 。 buckets 。 getIamPolicy | 探索Google Cloud Storage儲存桶的相關資訊。 


| - cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.getIamPolicy
- cloudkms.cryptoKeys.list
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keycloues.get
- cloudkms.keyclogs.getIamPolicy
- cloudkms.keyclings 。 list
- cloudkms.keyRings.setIamPolicy | 可在 BlueXP 備份和恢復激活嚮導中選擇您自己的客戶託管密鑰，而無需使用默認的 Google 託管加密密鑰。 
|===


== 變更記錄

新增和移除權限時、我們會在下方各節中加以註記。



=== 2023 年 2 月 6 日

已將下列權限新增至此原則：

* compute.instances.updateNetworkInterface


此權限為Cloud Volumes ONTAP 必填欄位。



=== 2023 年 1 月 27 日

已將下列權限新增至原則：

* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyclous.Get
* cloudkms.keyclas.getIamPolicy
* cloudkms.keyRings.setIamPolicy


BlueXP 備份與還原需要這些權限。
