---
sidebar: sidebar 
permalink: reference-host-requirements-aws.html 
keywords: cpu requirements, ram requirements, aws requirements, aws host requirements, connector host requirements, ec2 instance type 
summary: Connector 軟體必須在符合特定作業系統需求、 RAM 需求、連接埠需求等的主機上執行。如果您打算手動安裝 Connector 、則應確保主機符合這些需求。 
---
= 檢閱連接器主機安裝 AWS 的需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connector 軟體必須在符合特定作業系統需求、 RAM 需求、連接埠需求等的主機上執行。如果您打算手動安裝 Connector 、則應確保主機符合這些需求。

當您從 BlueXP 或 AWS Marketplace 部署 Connector 時、映像會包含所需的作業系統和軟體元件。

專用主機:: 與其他應用程式共用的主機不支援 Connector 。主機必須是專屬主機。
支援的作業系統::
+
--
* Ubuntu 22.04
* CentOS 7.6、7.7、7.8及7.9
* Red Hat Enterprise Linux 7.6 、 7.7 、 7.8 和 7.9
+
主機必須向 Red Hat Subscription Management 登錄。如果主機尚未登錄、則無法在 Connector 安裝期間存取儲存庫來更新所需的協力廠商軟體。

+
這些作業系統的英文版本支援 Connector 。



--
Hypervisor:: 需要經認證可執行 Ubuntu 、 CentOS 或 Red Hat Enterprise Linux 的裸機或託管 Hypervisor 。
+
--
https://access.redhat.com/certified-hypervisors["Red Hat 解決方案：哪些 Hypervisor 已通過認證、可執行 Red Hat Enterprise Linux ？"^]

--
CPU:: 4 個核心或 4 個 vCPU
RAM:: 14 GB
AWS EC2 執行個體類型:: 符合上述 CPU 和 RAM 需求的執行個體類型。建議使用T3.xLarge。
金鑰配對:: 當您從 BlueXP 或 AWS Marketplace 建立 Connector 時、您需要選取 EC2 金鑰配對來搭配執行個體使用。
/opt 中的磁碟空間:: 必須有100 GiB的可用空間
/var.中的磁碟空間:: 必須提供20 GiB的空間
Docker引擎:: 安裝Connector之前、主機上必須安裝Docker Engine 19.3.1版或更新版本。 https://docs.docker.com/engine/install/["檢視安裝指示"^]

