---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, httpstokens 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。

這些限制僅適用於BlueXP的設定與管理：Connector、SaaS平台等。



== 連接器限制



=== EC2 執行個體需要 IMDSv1

在使用標準模式或受限模式時、在 AWS 中的 EC2 執行個體上手動安裝 Connector 軟體之前、您必須確保 EC2 執行個體使用 Instance 中繼資料服務版本 1 （ IMDSv1 ）。IMSv2 不支援 Connector 。

由於 IMDSv2 現在是新 EC2 執行個體的預設版本、因此您必須修改執行個體中繼資料選項、才能還原 IMDSv1 的使用。

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html#modify-restore-IMDSv1["AWS 文件：還原 IMDSv1 的使用"^]



=== 不應變更預設 EC2 執行個體設定

當您從 BlueXP 或 AWS Marketplace 在 AWS 中部署 Connector 時、依預設會設定下列 EC2 執行個體設定：

* IMDSv2 設為選用
* 已將 HttpToken 設定為選用


這些設定不應變更為必要。將這些設定變更為「必要」會影響 Connector 和 Cloud Volumes ONTAP 的可用度。



=== 可能與172範圍內的IP位址發生衝突

BlueXP部署連接器時、會有兩個介面、其中IP位址介於172.17.0.0/16和172.18.0.0/16範圍內。

如果您的網路已設定具有上述任一範圍的子網路、則可能會遇到來自BlueXP的連線故障。例如ONTAP 、在BlueXP中探索內部的功能不全的叢集可能會失敗。

請參閱知識庫文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["BlueXP Connector IP與現有網路衝突"] 如需如何變更連接器介面的IP位址的指示。



=== 不支援SSL解密

BlueXP不支援啟用SSL解密的防火牆組態。如果啟用SSL解密、則錯誤訊息會顯示在BlueXP中、而Connector執行個體則顯示為非作用中。

為了增強安全性、您可以選擇 link:task-installing-https-cert.html["安裝由憑證授權單位（CA）簽署的HTTPS憑證"]。



=== 載入本機UI時顯示空白頁面

如果您載入在 Connector 上執行的 Web 型主控台、介面可能會有時無法顯示、只會出現空白頁面。

此問題與快取問題有關。因應措施是使用無痕式或私有網路瀏覽器工作階段。



=== 不支援共享 Linux 主機

與其他應用程式共用的VM不支援Connector。VM必須專用於Connector軟體。



=== 第三方代理程式與擴充功能

Connector VM不支援協力廠商代理程式或VM擴充。
