---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  身分識別與存取管理包含數個預先定義的角色、您可以指派給組織成員。 
---
= 預先定義的 BlueXP  IAM 角色和權限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  身分識別與存取管理（ IAM ）包含數個預先定義的角色、您可以在不同的資源階層層級中指派給組織成員。指派這些角色之前、您應該先瞭解每個角色所包含的權限。角色分為三類：平台，應用程式和資料服務。



== 平台角色

平台角色是您可以指派給使用者的最廣泛角色，並允許廣泛的 BlueXP  管理權限，包括指派角色和新增使用者，以及執行所有 BlueXP  功能。BlueXP  IAM 包含兩個平台角色：組織管理和資料夾或專案管理。兩個 BlueXP  IAM 平台角色的主要差異在於範圍。



=== 組織管理員

允許使用者不受限制地存取組織內的所有專案和資料夾，將成員新增至任何專案或資料夾，以及執行任何 BlueXP  工作和使用任何資料服務。



=== 資料夾或專案管理員

允許使用者不受限制地存取指派給他們的特定專案和資料夾。可以將成員新增至他們所管理的專案或資料夾，以及執行任何 BlueXP  工作，並使用其指派的資料夾或專案中的任何資料服務。

資料夾或專案管理員角色無法建立連接器。



=== 平台角色比較表

[cols="24,19,19"]
|===
| 工作 | 組織管理員 | 資料夾或專案管理員 


| 建立連接器 | 是的 | 否 


| 建立，修改或刪除工作環境（使用 BlueXP  畫布新增或探索新資源） | 是的 | 是的 


| 建立專案 / 資料夾，包括刪除 | 是的 | 否 


| 重新命名現有專案 / 資料夾 | 是的 | 是的 


| 指派角色並新增使用者 | 是的 | 是的 


| 將資源與資料夾和專案建立關聯 | 是的 | 是的 


| 將連接器與資料夾和專案建立關聯 | 是的 | 否 


| 從資料夾和專案中移除連接器 | 是的 | 否 


| 管理連接器（編輯憑證，設定等） | 是的 | 否 


| 從「設定」 > 「認證」管理認證 | 是的 | 是的 


| 檢視 BlueXP  時間表 | 是的 | 是的 


| 使用 BlueXP  服務 | 是的 | 是的 


| 註冊 BlueXP  以取得支援並提交案例 | 是的 | 是的 
|===
大型跨國組織在 BlueXP  中扮演組織角色的範例:: XYZ Corporation 是一家跨國企業，其目標是根據北美，歐洲和亞太地區等地理區域，將資料儲存資源的存取區隔開來。他們希望每個區域都能完全掌控自己的資源，同時維持集中監督。
+
--
為達成此目標，指派 XYZ 公司 BlueXP  組織管理員角色的人員會建立初始工作環境，然後在 BlueXP  中為每個區域建立個別的資料夾。每個區域的資料夾都包含與該區域相關的專案（含相關資源）。組織管理員會在每個個別區域指派 BlueXP  使用者資料夾 / 專案管理員角色。

完成初始設定後，具有資料夾或專案管理員角色的區域管理員即可建立新的工作環境，並在其區域內新增使用者。這些區域管理員也可以新增 / 移除 / 重新命名指派給他們的資料夾和專案。組織管理員會繼承任何新工作環境或資源的權限，維持整個組織的儲存使用率可見度。

--




== 應用程式角色

應用程式角色可讓您存取 BlueXP  應用程式，例如 Active IQ 數位顧問（也稱為數位顧問）。



=== 儲存管理員

讓使用者能夠在 BlueXP  中執行儲存管理功能，例如軟體更新，以及建立和刪除 BlueXP  工作環境。

權限:: 可檢視 BlueXP  畫布。可建立及管理 BlueXP  連接器。擁有 BlueXP  儲存健全狀況和治理功能的讀取 / 寫入存取權，包括下列項目：
+
--
* 數位顧問
* 營運恢復能力
* 軟體更新（可執行軟體更新）
* 數位錢包
* 經濟效益
* 永續發展儀表板
* 警示


--




=== 儲存檢視器

提供 BlueXP  健全狀況與治理功能的唯讀存取權。此角色通常指派給負責監控組織儲存資源健全狀況的使用者。具有此角色的使用者可以在 BlueXP  中檢視多個應用程式，以建立軟體更新計畫，效率計畫，以及檢視整體儲存健全狀況。

權限:: 具有 BlueXP  儲存健全狀況和治理功能的唯讀存取權，包括：
+
--
* 數位顧問
* 營運恢復能力
* 軟體更新（可下載升級計畫）
* 數位錢包
* 經濟效益
* 永續發展儀表板
* 警示


--




== 資料服務角色

資料服務角色可讓使用者存取組織，專案或資料夾內的資料服務。



=== SnapCenter 管理

提供從內部部署 ONTAP 叢集備份快照的功能、使用應用程式的 BlueXP  備份與還原功能。

權限:: 擁有此角色的成員可在 BlueXP  中完成下列動作：
+
--
* 從「備份與還原」 > 「應用程式」中完成任何動作
* 管理其擁有權限的專案和資料夾中的所有工作環境
* 使用所有 BlueXP  服務


--




=== 分類檢視器

提供檢視 BlueXP  分類掃描結果的能力。

權限:: 檢視法規遵循資訊、並針對擁有存取權限的資源產生報告。這些使用者無法啟用或停用掃描磁碟區、儲存區或資料庫架構。
+
--
擁有此角色的成員無法使用其他動作。

--




== 相關連結

* link:concept-identity-and-access-management.html["瞭解 BlueXP  身分識別與存取管理"]
* link:task-iam-get-started.html["BlueXP  IAM 入門"]
* link:task-iam-manage-members-permissions.html["管理 BlueXP  成員及其權限"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["瞭解 BlueXP  IAM 的 API"^]

