---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 當您使用透過 SaaS 層提供的 BlueXP 網路型主控台時、它會在完成一些管理工作時與多個端點連絡。存取 BlueXP 主控台的電腦應與這些端點建立連線。 
---
= 為 BlueXP  主控台準備網路
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
當您使用透過 SaaS 層提供的 BlueXP 網路型主控台時、它會在完成一些管理工作時與多個端點連絡。存取 BlueXP 主控台的電腦應與這些端點建立連線。

從 BlueXP 主控台完成特定動作時、會從使用者的電腦聯絡這些端點。您也應該參閱 Connector 的網路需求、以及特定的 BlueXP 服務。如需詳細資訊、請參閱本頁結尾的相關連結。

[cols="2*"]
|===
| 端點 | 目的 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | 當您使用 BlueXP 網路型主控台時、您的網路瀏覽器會連絡這些 URL 。 


| \https://aiq.netapp.com | 需要存取 BlueXP 數位顧問。 


 a| 
AWS 服務（ amazonaws.com):

* CloudForation
* 彈性運算雲端（ EC2 ）
* 金鑰管理服務（ KMS ）
* 安全性權杖服務（ STOS ）
* 簡易儲存服務（ S3 ）

| 需要在AWS中部署從BlueXP部署連接器。確切的端點取決於部署Connector的區域。 https://docs.aws.amazon.com/general/latest/gr/rande.html["如需詳細資料、請參閱 AWS 文件。"^] 


| \https://management.azure.com

\https://login.microsoftonline.com | 在大多數Azure地區中部署來自BlueXP的Connector。 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | 需要在Azure Germany地區部署來自BlueXP的Connector。 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | 需要在Azure US Gov地區部署來自BlueXP的Connector。 


| \https://www.googleapis.com | 需要在Google Cloud中部署來自BlueXP的Connector。 


| \https://signin.b2c.netapp.com | 需要更新NetApp 支援網站 驗證（NSS）認證或新增新的NSS認證至BlueXP。 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | 您的網頁瀏覽器會連線至這些端點、以便透過BlueXP進行集中式使用者驗證。 


| \https://widget.intercom.io | 產品內對談可讓您與 NetApp 雲端專家交談。 
|===
除了這些端點之外、您還需要確保 Connector 具備對外網際網路存取權、以便聯絡特定端點、以進行日常作業。您可以依照下一節中的連結、找到這些端點的清單。

.相關資訊
* 準備連接器的網路連線
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["設定 AWS 網路"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["設定 Azure 網路"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["設定 Google Cloud 網路"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["設定內部網路"]


* 為 BlueXP 服務做好網路準備
+
請參閱每項 BlueXP 服務的文件。

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXP文件"^]


