---
sidebar: sidebar 
permalink: task-set-up-networking-azure.html 
keywords: azure networking, networking, vnet, subnet, azure region, connections, outbound connections, endpoints, urls, proxy, proxy server 
summary: 設定您的網路、讓 Connector 能夠管理混合雲環境中的資源和程序。例如、您需要確保目標網路可以使用連線、而且可以使用輸出網際網路存取。 
---
= 設定 Azure 網路
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
設定您的網路、讓 Connector 能夠管理混合雲環境中的資源和程序。例如、您需要確保目標網路可以使用連線、而且可以使用輸出網際網路存取。



== vnet 和子網路

建立 Connector 時、您需要指定 Connector 應位於的 vnet 和子網路。



== Azure地區

如果您使用 Cloud Volumes ONTAP 、 Connector 應部署在與其管理的 Cloud Volumes ONTAP 系統所在的同一個 Azure 區域、或部署在中 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure區域配對"^] 適用於整個系統。Cloud Volumes ONTAP這項需求可確保Cloud Volumes ONTAP Azure Private Link連線可用於連接至相關的儲存帳戶。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["瞭Cloud Volumes ONTAP 解如何使用Azure Private Link"^]



== 連線至目標網路

Connector 需要網路連線、才能連線到您計畫建立和管理工作環境的位置。



== 傳出網際網路存取

您部署Connector的網路位置必須具有傳出網際網路連線。從 BlueXP 主控台部署 Connector 時、也需要從網頁瀏覽器進行輸出網際網路存取。



=== 從 BlueXP 主控台連絡的端點

當您使用透過 SaaS 層提供的 BlueXP 網路型主控台時、它會與多個端點聯絡、以完成資料管理工作。這包括透過 BlueXP 主控台聯絡以部署 Connector 的端點。

link:reference-networking-saas-console.html["檢視從 BlueXP 主控台連絡的端點清單"]。



=== 手動安裝期間聯絡的端點

當您在自己的 Linux 主機上手動安裝 Connector 時、 Connector 的安裝程式需要在安裝過程中存取下列 URL ：

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io


主機可能會在安裝期間嘗試更新作業系統套件。主機可聯絡不同的鏡射站台、以取得這些 OS 套件。



=== 已從 Connector 聯絡的端點

Connector 需要外傳網際網路存取才能連絡下列端點、以便管理公有雲環境中的資源和程序、以進行日常營運。

[cols="2a,1a"]
|===
| 端點 | 目的 


 a| 
\https://management.azure.com
\https://login.microsoftonline.com
\https://blob.core.windows.net
\https://core.windows.net
 a| 
管理Azure公共區域的資源。



 a| 
\https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn
\https://blob.core.chinacloudapi.cn
\https://core.chinacloudapi.cn
 a| 
管理Azure中國地區的資源。



 a| 
\https://support.netapp.com
 a| 
以取得授權資訊、並將AutoSupport 資訊傳送給NetApp支援部門。



 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://api.cloud.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

\https://netapp-cloud-account.auth0.com/userinfo
 a| 
在BlueXP中提供SaaS功能與服務。

請注意、 Connector 目前正在聯絡「 cloudmanager.cloud.netapp.com" 」、但在即將推出的版本中、會開始聯絡「 api.bluexp.netapp.com" 」。



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
升級Connector及其Docker元件。

|===


== Proxy伺服器

如果您的組織需要為所有傳出的網際網路流量部署 Proxy 伺服器、請取得下列關於 HTTP 或 HTTPS Proxy 的資訊。您必須在安裝期間提供此資訊。

* IP 位址
* 認證資料
* HTTPS憑證




== 連接埠

除非您啟動連接器、或使用連接器做為 Proxy 、將 AutoSupport 訊息從 Cloud Volumes ONTAP 傳送至 NetApp 支援、否則不會有傳入的流量傳入連接器。

* HTTP（80）和HTTPS（443）可存取本機UI、在極少數情況下使用。
* 只有在需要連線至主機進行疑難排解時、才需要SSH（22）。
* 如果您在無法使用輸出網際網路連線的子網路中部署 Cloud Volumes ONTAP 系統、則需要透過連接埠 3128 進行輸入連線。
+
如果 Cloud Volumes ONTAP 系統沒有輸出網際網路連線來傳送 AutoSupport 訊息、 BlueXP 會自動將這些系統設定為使用 Connector 隨附的 Proxy 伺服器。唯一的需求是確保連接器的安全群組允許透過連接埠3128進行傳入連線。部署Connector之後、您需要開啟此連接埠。





== IP位址限制

可能與172範圍內的IP位址發生衝突。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["深入瞭解此限制"]。
