---
sidebar: sidebar 
permalink: task-installing-linux.html 
keywords: install connector, manually install connector, install connector software, installation, installing, linux, installer, software, on prem, on-prem, silent, configurations, ec2, vm, ports, ram, operating system, os, host, requirement, requirements, hypervisor, disk, space, mysql, centos, rhel, red hat, cpu, disk space 
summary: 建立Connector最常見的方法是直接從BlueXP或雲端供應商的市場建立Connector。但您可以選擇在網路或雲端的現有 Linux 主機上下載並安裝 Connector 軟體。這些步驟僅適用於可存取網際網路的主機。 
---
= 在現有的Linux主機上安裝連接器、該主機可存取網際網路
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
建立Connector最常見的方法是直接從BlueXP或雲端供應商的市場建立Connector。但您可以選擇在網路或雲端的現有 Linux 主機上下載並安裝 Connector 軟體。這些步驟僅適用於可存取網際網路的主機。

link:concept-connectors.html["瞭解部署Connector的其他方法"]。


NOTE: 如果您想要在Cloud Volumes ONTAP Google Cloud中建立一個不完整的系統、那麼您也必須在Google Cloud上執行一個Connector。您無法使用在AWS、Azure或內部執行的Connector。



== 驗證主機需求

Connector 軟體必須在符合特定作業系統需求、 RAM 需求、連接埠需求等的主機上執行。

需要專用主機:: 與其他應用程式共用的主機不支援 Connector 。主機必須是專屬主機。
CPU:: 4 個核心或 4 個 vCPU
RAM:: 14 GB
AWS EC2 執行個體類型:: 符合上述 CPU 和 RAM 需求的執行個體類型。建議使用T3.xLarge。
Azure VM 大小:: 符合上述 CPU 和 RAM 需求的執行個體類型。我們建議使用 DS3 v2 。
GCP 機器類型:: 符合上述 CPU 和 RAM 需求的執行個體類型。建議使用n2-Standard-4。
+
--
Google Cloud支援Connector的VM執行個體、其作業系統可支援此連接器 https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["防護VM功能"^]

--
支援的作業系統::
+
--
* CentOS 7.6、7.7、7.8及7.9
* Red Hat Enterprise Linux 7.6、7.7、7.8、7.9、8.6、 和8.7%
+
Red Hat Enterprise Linux 系統必須在 Red Hat 訂購管理中註冊。如果未登錄、系統將無法在 Connector 安裝期間存取儲存庫來更新所需的協力廠商軟體。

+
這些作業系統的英文版本支援 Connector 。



--
Hypervisor:: 通過認證可執行 CentOS 或 Red Hat Enterprise Linux 的裸機或託管 Hypervisorhttps://access.redhat.com/certified-hypervisors["Red Hat 解決方案：哪些 Hypervisor 已通過認證、可執行 Red Hat Enterprise Linux ？"^]
/opt 中的磁碟空間:: 必須有100 GiB的可用空間
/var.中的磁碟空間:: 必須提供20 GiB的空間
Docker引擎:: 安裝Connector之前、主機上必須安裝Docker Engine 19.3.1版或更新版本。 https://docs.docker.com/engine/install/["檢視安裝指示"^]
傳出網際網路存取:: Connector安裝程式必須在安裝過程中存取下列URL：
+
--
* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://cloudmanagerinfraprod.azurecr.io
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net


主機可能會在安裝期間嘗試更新作業系統套件。主機可聯絡不同的鏡射站台、以取得這些 OS 套件。

--




== 安裝Connector

驗證是否有支援的Linux主機之後、您就可以取得Connector軟體、然後再進行安裝。

.您需要的產品
* 安裝Connector的root權限。
* Proxy伺服器的詳細資料、如果需要Proxy才能從Connector存取網際網路。支援HTTP和HTTPS。
+
您可以選擇在安裝後設定Proxy伺服器、但需要重新啟動Connector。

* 如果Proxy伺服器使用HTTPS、則為CA簽署的憑證。


.關於這項工作
* 安裝會安裝 AWS 命令列工具（ awscli ）、以啟用 NetApp 支援的還原程序。
+
如果您收到安裝 awscli 失敗的訊息、您可以放心忽略該訊息。無需使用工具、連接器即可順利運作。

* NetApp 支援網站上提供的安裝程式可能是較早的版本。安裝後、如果有新版本可用、 Connector 會自動自行更新。


.步驟
. 確認已啟用並執行Docker。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. 如果主機上已設定_http或_https或proxy_系統變數、請將其移除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果您未移除這些系統變數、安裝將會失敗。

. 從下載Connector軟體 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 支援網站"^]，然後將其複製到 Linux 主機。
+
您應該下載連接器安裝程式、以便在網路或雲端上使用。

. 指派執行指令碼的權限。
+
[source, cli]
----
chmod +x OnCommandCloudManager-V3.9.23
----
. 執行安裝指令碼。
+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.23 --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
-Proxy和--cacert參數是可選的。如果您有Proxy伺服器、則必須輸入所示的參數。安裝程式不會提示您提供Proxy的相關資訊。

+
以下是使用兩個選用參數的命令範例：

+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.23 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-Proxy會使用下列其中一種格式、將Connector設定為使用HTTP或HTTPS Proxy伺服器：

+
** \http://address:port
** \http://username:password@address:port
** \https://address:port
** \https://username:password@address:port


+
-cacert指定用於連接器與Proxy伺服器之間HTTPS存取的CA簽署憑證。僅當您指定HTTPS Proxy伺服器時、才需要此參數。



.結果
現在已安裝Connector。安裝結束時、如果您指定Proxy伺服器、Connector服務（occm）會重新啟動兩次。



== 設定Connector

註冊或登入、然後設定Connector以使用您的帳戶。

.步驟
. 開啟網頁瀏覽器並輸入下列 URL ：
+
https://_ipaddress_[]

+
_ipaddress_ 可以是 localhost 、私有 IP 位址或公有 IP 位址、視主機的組態而定。例如、如果連接器位於沒有公有 IP 位址的公有雲中、您必須輸入連接至連接器主機之主機的私有 IP 位址。

. 註冊或登入。
. 如果您在Google Cloud中安裝Connector、請設定具有BlueXP所需權限的服務帳戶、以便在Cloud Volumes ONTAP 專案中建立及管理各種系統。
+
.. https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["在 GCP 中建立角色"^] 這包括在中定義的權限 link:reference-permissions-gcp.html["GCP的連接器原則"]。
.. https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["建立 GCP 服務帳戶、並套用您剛建立的自訂角色"^]。
.. https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["將此服務帳戶與 Connector VM 建立關聯"^]。
.. 如果您想要在 Cloud Volumes ONTAP 其他專案中部署 https://cloud.google.com/iam/docs/granting-changing-revoking-access#granting-console["將具有BlueXP角色的服務帳戶新增至該專案、以授予存取權"^]。您必須針對每個專案重複此步驟。


. 登入之後、請設定BlueXP：
+
.. 指定要與Connector建立關聯的NetApp帳戶。
+
link:concept-netapp-accounts.html["瞭解NetApp客戶"]。

.. 輸入系統名稱。




.結果
現在已安裝Connector、並使用您的NetApp帳戶進行設定。在您建立新的工作環境時、BlueXP會自動使用此Connector。

.完成後
設定權限、讓BlueXP能夠管理公有雲環境中的資源和程序：

* AWS ： link:task-adding-aws-accounts.html["設定AWS帳戶、然後將其新增至BlueXP"]
* Azure ： link:task-adding-azure-accounts.html["設定Azure帳戶、然後將其新增至BlueXP"]
* Google Cloud：請參閱上述步驟3

