---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: 若要在您自己的 Linux 主機上手動安裝 Connector 、您必須檢閱主機需求、設定網路、準備 Google Cloud 權限、啟用 Google Cloud API 、安裝 Connector 、然後提供您準備的權限。 
---
= 在 Google Cloud 中手動安裝 Connector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要在您自己的 Linux 主機上手動安裝 Connector 、您必須檢閱主機需求、設定網路、準備 Google Cloud 權限、啟用 Google Cloud API 、安裝 Connector 、然後提供您準備的權限。

.開始之前
您應該檢閱 link:reference-limitations.html["連接器限制"]。



== 步驟 1 ：檢閱主機需求

Connector 軟體必須在符合特定作業系統需求、 RAM 需求、連接埠需求等的主機上執行。

專用主機:: 與其他應用程式共用的主機不支援 Connector 。主機必須是專屬主機。
支援的作業系統::
+
--
* Ubuntu 22.04
* CentOS 7.6、7.7、7.8及7.9
* Red Hat Enterprise Linux 7.6 、 7.7 、 7.8 和 7.9
+
主機必須向 Red Hat Subscription Management 登錄。如果主機尚未登錄、則無法在 Connector 安裝期間存取儲存庫來更新所需的協力廠商軟體。

+
這些作業系統的英文版本支援 Connector 。



--
Hypervisor:: 需要經認證可執行 Ubuntu 、 CentOS 或 Red Hat Enterprise Linux 的裸機或託管 Hypervisor 。
+
--
https://access.redhat.com/certified-hypervisors["Red Hat 解決方案：哪些 Hypervisor 已通過認證、可執行 Red Hat Enterprise Linux ？"^]

--
CPU:: 4 個核心或 4 個 vCPU
RAM:: 14 GB
Google Cloud 機器類型:: 符合上述 CPU 和 RAM 需求的執行個體類型。我們建議使用 n2 標準 4 。
+
--
Google Cloud支援Connector的VM執行個體、其作業系統可支援此連接器 https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["防護VM功能"^]

--
/opt 中的磁碟空間:: 必須有100 GiB的可用空間
/var.中的磁碟空間:: 必須提供20 GiB的空間
Docker引擎:: 安裝Connector之前、主機上必須安裝Docker Engine 19.3.1版或更新版本。 https://docs.docker.com/engine/install/["檢視安裝指示"^]




== 步驟 2 ：設定網路

設定您的網路、讓 Connector 能夠管理混合雲環境中的資源和程序。例如、您需要確保目標網路可以使用連線、而且可以使用輸出網際網路存取。

連線至目標網路:: Connector 需要網路連線、才能連線到您計畫建立和管理工作環境的位置。例如、您計畫在內部部署環境中建立 Cloud Volumes ONTAP 系統或儲存系統的網路。


傳出網際網路存取:: 您部署 Connector 的網路位置必須具有傳出網際網路連線、才能連絡特定端點。


手動安裝期間聯絡的端點:: 當您在自己的 Linux 主機上手動安裝 Connector 時、 Connector 的安裝程式需要在安裝過程中存取下列 URL ：
+
--
* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io
+
主機可能會在安裝期間嘗試更新作業系統套件。主機可聯絡不同的鏡射站台、以取得這些 OS 套件。



--


已從 Connector 聯絡的端點:: Connector 需要外傳網際網路存取才能連絡下列端點、以便管理公有雲環境中的資源和程序、以進行日常營運。
+
--
[cols="2a,1a"]
|===
| 端點 | 目的 


 a| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
管理Google Cloud中的資源。



 a| 
\https://support.netapp.com
\https://mysupport.netapp.com
 a| 
以取得授權資訊、並將AutoSupport 資訊傳送給NetApp支援部門。



 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

\https://netapp-cloud-account.auth0.com
 a| 
在BlueXP中提供SaaS功能與服務。

請注意、 Connector 目前正在聯絡「 cloudmanager.cloud.netapp.com" 」、但在即將推出的版本中、會開始聯絡「 api.bluexp.netapp.com" 」。



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
升級Connector及其Docker元件。

|===
--


Proxy伺服器:: 如果您的組織需要為所有傳出的網際網路流量部署 Proxy 伺服器、請取得下列關於 HTTP 或 HTTPS Proxy 的資訊。您必須在安裝期間提供此資訊。
+
--
* IP 位址
* 認證資料
* HTTPS憑證


--


連接埠:: 除非您啟動連接器、或使用連接器做為 Proxy 、將 AutoSupport 訊息從 Cloud Volumes ONTAP 傳送至 NetApp 支援、否則不會有傳入的流量傳入連接器。
+
--
* HTTP（80）和HTTPS（443）可存取本機UI、在極少數情況下使用。
* 只有在需要連線至主機進行疑難排解時、才需要SSH（22）。
* 如果您在無法使用輸出網際網路連線的子網路中部署 Cloud Volumes ONTAP 系統、則需要透過連接埠 3128 進行輸入連線。
+
如果 Cloud Volumes ONTAP 系統沒有輸出網際網路連線來傳送 AutoSupport 訊息、 BlueXP 會自動將這些系統設定為使用 Connector 隨附的 Proxy 伺服器。唯一的需求是確保連接器的安全群組允許透過連接埠3128進行傳入連線。部署Connector之後、您需要開啟此連接埠。



--




== 步驟 3 ：設定 Connector 的權限

需要 Google Cloud 服務帳戶、才能為 Connector 提供 BlueXP 在 Google Cloud 中管理資源所需的權限。建立 Connector 時、您需要將此服務帳戶與 Connector VM 建立關聯。

.步驟
. 在 Google Cloud 中建立自訂角色：
+
.. 建立包含的內容的 YAML 檔案 link:reference-permissions-gcp.html["Connector 的服務帳戶權限"]。
.. 從 Google Cloud 啟動 Cloud Shell 。
.. 上傳包含必要權限的 YAML 檔案。
.. 使用建立自訂角色 `gcloud iam roles create` 命令。
+
以下範例在專案層級建立名為「 Connector 」的角色：

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud 文件：建立及管理自訂角色"^]



. 在 Google Cloud 中建立服務帳戶、並將角色指派給服務帳戶：
+
.. 從 IAM & Admin 服務中、選取 * 服務帳戶 > 建立服務帳戶 * 。
.. 輸入服務帳戶詳細資料、然後選取 * 建立並繼續 * 。
.. 選取您剛建立的角色。
.. 完成剩餘步驟以建立角色。
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud 文件：建立服務帳戶"^]



. 如果您計畫在Cloud Volumes ONTAP Connector所在專案的不同專案中部署支援功能、則需要提供Connector的服務帳戶、以便存取這些專案。
+
例如、假設Connector在專案1中、您想在Cloud Volumes ONTAP 專案2中建立一套支援系統。您必須在專案2中授予服務帳戶存取權。

+
.. 從 IAM & Admin 服務中、選取您要建立 Cloud Volumes ONTAP 系統的 Google Cloud 專案。
.. 在「* IAM *」頁面上、選取「*授予存取權*」、並提供所需的詳細資料。
+
*** 輸入Connector服務帳戶的電子郵件。
*** 選取Connector的自訂角色。
*** 選擇*保存*。




+
如需詳細資料、請參閱 https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud文件"^]



.結果
已設定Connector VM的服務帳戶。



== 步驟 4 ：設定共用 VPC 權限

如果您使用共享 VPC 將資源部署到服務專案中、則需要準備權限。

此表供參考、當IAM組態完成時、您的環境應反映權限表。

.檢視共享的 VPC 權限
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| 身分識別 | 建立者 | 裝載於 | 服務專案權限 | 主機專案權限 | 目的 


| Google 帳戶以部署 Connector | 自訂 | 服務專案  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["Connector 部署原則"]
 a| 
compute.networkUser
| 在服務專案中部署Connector 


| 連接器服務帳戶 | 自訂 | 服務專案  a| 
link:reference-permissions-gcp.html["Connector 服務帳戶原則"]
| compute.networkUser

部署manager.manager | 在Cloud Volumes ONTAP 服務專案中部署及維護功能與服務 


| 服務帳戶Cloud Volumes ONTAP | 自訂 | 服務專案 | 儲存設備管理

成員：serviceAccount.user的BlueXP服務帳戶 | 不適用 | （選用）用於資料分層和 BlueXP 備份與還原 


| Google API服務代理程式 | Google Cloud | 服務專案  a| 
（預設）編輯器
 a| 
compute.networkUser
| 代表部署與Google Cloud API互動。允許BlueXP使用共享網路。 


| Google Compute Engine預設服務帳戶 | Google Cloud | 服務專案  a| 
（預設）編輯器
 a| 
compute.networkUser
| 代表部署部署部署部署Google Cloud執行個體和運算基礎架構。允許BlueXP使用共享網路。 
|===
附註：

. 只有當您未將防火牆規則傳遞給部署、並選擇讓BlueXP為您建立時、才需要在主機專案中部署manager.manager。如果未指定任何規則、則BlueXP會在主機專案中建立包含VPC0防火牆規則的部署。
. 只有當您未將防火牆規則傳遞至部署、並選擇讓BlueXP為您建立防火牆規則時、才需要使用Firewall.create和firewall.delete。這些權限位於BlueXP帳戶.yaml檔案中。如果您使用共用VPC部署HA配對、這些權限將用於建立VPC1、2和3的防火牆規則。對於所有其他部署、這些權限也會用於建立VPC0的規則。
. 對於資料分層、分層服務帳戶必須在服務帳戶上具有serviceAccount.user角色、而不只是在專案層級。目前、如果您在專案層級指派serviceAccount.user、則當您使用getIAMPolicy查詢服務帳戶時、不會顯示權限。


====


== 步驟 5 ：啟用 Google Cloud API

您必須先啟用數個 Google Cloud API 、才能在 Google Cloud 中部署 Cloud Volumes ONTAP 系統。

.步驟
. 在專案中啟用下列 Google Cloud API ：
+
** Cloud Deployment Manager V2 API
** 雲端記錄 API
** Cloud Resource Manager API
** 運算引擎 API
** 身分識別與存取管理（ IAM ） API
** 雲端金鑰管理服務（ KMS ） API
+
（僅當您打算使用 BlueXP 備份與還原搭配客戶管理的加密金鑰（ CMEK ）時才需要）





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud 文件：啟用 API"^]



== 步驟 6 ：安裝 Connector

完成先決條件後、您可以在自己的 Linux 主機上手動安裝軟體。

.開始之前
您應該擁有下列項目：

* 安裝Connector的root權限。
* Proxy伺服器的詳細資料、如果需要Proxy才能從Connector存取網際網路。
+
您可以選擇在安裝後設定Proxy伺服器、但需要重新啟動Connector。

* CA 簽署的憑證（如果 Proxy 伺服器使用 HTTPS 或 Proxy 是攔截 Proxy ）。


.關於這項工作
NetApp 支援網站上提供的安裝程式可能是舊版。安裝後、如果有新版本可用、 Connector 會自動自行更新。

.步驟
. 確認已啟用並執行Docker。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. 如果主機上已設定_http或_https或proxy_系統變數、請將其移除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果您未移除這些系統變數、安裝將會失敗。

. 從下載Connector軟體 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 支援網站"^]，然後將其複製到 Linux 主機。
+
您應該下載「線上」 Connector 安裝程式、以供您的網路或雲端使用。Connector 有獨立的「離線」安裝程式、但僅支援私有模式部署。

. 指派執行指令碼的權限。
+
[source, cli]
----
chmod +x Cloud-Manager-Connector-Cloud-<version>
----
+
其中、就是您下載的Connector版本<version> 。

. 執行安裝指令碼。
+
[source, cli]
----
 ./Cloud-Manager-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
-Proxy和--cacert參數是可選的。如果您有 Proxy 伺服器、則需要輸入如圖所示的參數。安裝程式不會提示您提供Proxy的相關資訊。

+
以下是使用兩個選用參數的命令範例：

+
[source, cli]
----
 ./Cloud-Manager-Connector-Cloud-V3.9.32 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-Proxy會使用下列其中一種格式、將Connector設定為使用HTTP或HTTPS Proxy伺服器：

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
請注意下列事項：

+
*** 使用者可以是本機使用者或網域使用者。
*** 對於網域使用者、您必須使用上方所示的 \ 的 ASCII 碼。
*** BlueXP不支援包含@字元的密碼。




+
-cacert指定用於連接器與Proxy伺服器之間HTTPS存取的CA簽署憑證。只有當您指定 HTTPS Proxy 伺服器或 Proxy 是攔截 Proxy 時、才需要此參數。

. 等待安裝完成。
+
安裝結束時、如果您指定Proxy伺服器、Connector服務（occm）會重新啟動兩次。

. 從連線至 Connector 虛擬機器的主機開啟網頁瀏覽器、然後輸入下列 URL ：
+
https://_ipaddress_[]

. 登入後、設定 Connector ：
+
.. 指定與 Connector 相關聯的 BlueXP 帳戶。
.. 輸入系統名稱。
.. 在 * 您是在安全的環境中執行？ * 保持停用限制模式。
+
您應該保持停用受限模式、因為這些步驟說明如何在標準模式中使用 BlueXP 。只有當您擁有安全的環境、而且想要中斷此帳戶與 BlueXP 後端服務的連線時、才應啟用受限模式。如果是這樣、 link:task-quick-start-restricted-mode.html["請依照步驟、以受限模式開始使用 BlueXP"]。

.. 選取 * 開始 * 。




.結果
Connector 現已安裝、並已使用您的 BlueXP 帳戶進行設定。



== 步驟 7 ：提供 BlueXP 的權限

您必須提供 BlueXP 先前設定的 Google Cloud 權限。提供權限可讓 BlueXP 在 Google Cloud 中管理您的資料和儲存基礎架構。

.步驟
. 前往 Google Cloud 入口網站、將服務帳戶指派給 Connector VM 執行個體。
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Google Cloud 文件：變更執行個體的服務帳戶和存取範圍"^]

. 如果您想要管理其他 Google Cloud 專案中的資源、請將具有 BlueXP 角色的服務帳戶新增至該專案、以授予存取權。您必須針對每個專案重複此步驟。


.結果
BlueXP 現在擁有代表您在 Google Cloud 中執行動作所需的權限。
