---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: connector operating system, connector maintenance, vm maintenance, os updates, operating system updates, stop connector, restart connector 
summary: 在 Connector 主機上維護作業系統是您的責任。例如、您應該遵循公司的作業系統發佈標準程序、將安全性更新套用至 Connector 主機上的作業系統。 
---
= 維護 Connector VM 和作業系統
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
維護連接器主機上的作業系統是您（客戶）的責任。例如，您（客戶）應依照公司作業系統分發的標準流程，將安全性更新套用至連接器主機上的作業系統。


TIP: 如果您有現有的 Connector 、您應該知道 link:reference-connector-operating-system-changes.html["支援的 Linux 作業系統變更"]。



== 作業系統修補程式和 Connector

套用作業系統安全性修補程式時、不需要停止 Connector 主機上的任何服務。



== VM 或執行個體類型

如果您直接從 BlueXP 建立 Connector 、 BlueXP 會使用預設組態、在雲端供應商中部署虛擬機器執行個體。建立 Connector 之後、不應變更為 CPU 或 RAM 較少的較小 VM 執行個體。

CPU 和 RAM 需求如下：

CPU:: 8 個核心或 8 個 vCPU
RAM:: 32GB


link:reference-connector-default-config.html["瞭解連接器的預設組態"]。



== 監控磁碟空間

當 Connector VM 的磁碟空間不足時，BlueXP 會通知您。您可以在通知中心監控這些通知，或將其設定為發送電子郵件警報。解決磁碟空間問題是您的責任。link:ttps://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["查看 NetApp 知識庫文章"^]。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#notification-center["深入瞭解。"^]



== 停止並啟動 Connector VM

如果您需要停止然後啟動 Connector VM 、則應從雲端供應商的主控台或使用內部部署管理的標準程序來執行。

link:concept-connectors.html#connectors-must-be-operational-at-all-times["請注意、 Connector 必須隨時都能運作"]。



== 連線至Linux VM

如果您需要連線至執行Connector的Linux VM、可以使用雲端供應商提供的連線選項來執行。

AWS:: 在AWS中建立Connector執行個體時、您提供了AWS存取金鑰和秘密金鑰。您可以將此金鑰配對用於執行個體的SSH。EC2 Linux 執行個體的使用者名稱為 Ubuntu （對於在 2023 年 5 月之前建立的 Connectors 、使用者名稱為 EC2-user ）。
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS文件：連線至您的Linux執行個體"^]

--
Azure:: 在 Azure 中建立 Connector VM 時、您指定了使用者名稱、並選擇使用密碼或 SSH 公開金鑰進行驗證。使用您選擇的驗證方法來連線至VM。
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure文件：SSH進入VM"^]

--
Google Cloud:: 在Google Cloud中建立Connector時、您無法指定驗證方法。不過、您可以使用Google Cloud Console或Google Cloud CLI（gclCloud）連線至Linux VM執行個體。
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs：連線至Linux VM"^]

--




== 變更連接器的IP位址

如果貴企業需要、您可以變更由雲端供應商自動指派之Connector執行個體的內部IP位址和公有IP位址。

.步驟
. 依照雲端供應商的指示、變更連接器執行個體的本機IP位址或公有IP位址（或兩者）。
. 如果您變更了公用IP位址、而且需要連線至連接器上執行的本機使用者介面、請重新啟動連接器執行個體、以使用BlueXP登錄新的IP位址。
. 如果您變更了私有IP位址、請更新Cloud Volumes ONTAP 支援的還原組態檔案備份位置、以便將備份傳送到Connector上的新私有IP位址。
+
您需要更新每個 Cloud Volumes ONTAP 系統的備份位置。

+
.. 在 Cloud Volumes ONTAP CLI 中、將權限等級設為進階：
+
[source, cli]
----
set -privilege advanced
----
.. 執行下列命令以顯示目前的備份目標：
+
[source, cli]
----
system configuration backup settings show
----
.. 執行下列命令以更新備份目標的 IP 位址：
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== 編輯連接器的URI

新增及移除 Connector 的統一資源識別元（ URI ）。

.步驟
. 從 BlueXP 標頭中選取 * Connector* 下拉式清單。
. 選取 * 管理連接器 * 。
. 展開 *Connector URI* 列以檢視連接器的 URI 。
. 展開 *Connector URI* 列以檢視連接器的 URI 。
. 新增並移除 URI 、然後選取 * 套用 * 。

