= 連接器 3.9.52
:allow-uri-read: 




=== 連接器 3.9.52

此版本的 BlueXP  Connector 包括少量的安全性改善和錯誤修正，以及一些其他更新。

目前、 3.9.52 版本適用於標準模式和受限模式。



==== 支援 Docker 27 和 Docker 28

Connector 現在支援 Docker 27 和 Docker 28 。



==== Cloud Volumes ONTAP

當連接器不合規或停機超過 14 天時，Cloud Volumes ONTAP 節點不再關閉。當 Cloud Volumes ONTAP 失去對連接器的存取權限時，它仍會發送事件管理訊息。此變更是為了確保即使連接器長時間處於停機狀態，Cloud Volumes ONTAP 仍可繼續運作。它不會改變連接器的合規性要求。



=== BlueXP  中提供 Keystone 管理功能

BlueXP  中的 NetApp Keystone 試用版已新增對 Keystone 管理的存取權。您可以從 BlueXP  左側導覽列存取 NetApp Keystone Beta 的登錄頁面。



=== BlueXP  身分識別與存取管理（ IAM ）



==== 新的儲存管理角色

儲存管理員、系統健康專家和儲存檢視器角色可用，可以指派給使用者。

這些角色使您能夠管理組織中的誰可以發現和管理儲存資源，以及查看儲存健康資訊和執行軟體更新。

這些角色支援控制對以下儲存資源的存取：

* E系列系統
* 系統StorageGRID
* 內部部署ONTAP 的作業系統


您也可以使用這些角色來控制對下列 BlueXP 服務的存取：

* 軟體更新
* 數位顧問
* 營運恢復能力
* 經濟效益
* 永續性


已新增以下角色：

* *存儲管理員*
+
管理組織內儲存資源的儲存健康、治理和發現。該角色還可以對儲存資源執行軟體更新。

* *系統健康專家*
+
管理組織內儲存資源的儲存健康和治理。該角色還可以對儲存資源執行軟體更新。此角色不能修改或刪除工作環境。

* *儲存檢視器*
+
查看儲存健康資訊和治理資料。

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["瞭解存取角色。"^]


